### ISSUE TITLE
[FEATURE] Allow running "named" macros ontop of having them bind to a keyboard/mouse key

### ISSUE THREAD

**Issue by epifeny** [RusherDevelopment/rusherhack-issues#1025]
**What feature would you like to be added.**
I would like to be able to save a macro with a name and run it using the name via chat  `*macro run <name>` because I've already got too many keys bound.

**Is your feature request related to a problem? Please describe.**
NA

**Additional context**
![image](https://user-images.githubusercontent.com/89062105/131255252-fdf27294-83fd-48f0-ba32-13a59d64390f.png)

**Comment by John200410** [comment]
This will now be possible in v2.0
