### ISSUE TITLE
[FEATURE] silent swap anti weakness

### ISSUE THREAD

**Issue by ignelias** [RusherDevelopment/rusherhack-issues#1028]
silent anti weakness to hold a sword while silent placing crystals with weakness

**Comment by FluorideHistorian** [comment]
it already has silent swap for place

**Comment by LiquidSmokeBalls** [comment]
silent swap exists tho? :thonk:

**Comment by LiquidSmokeBalls** [comment]
but yea we def need silent antiweaknes lol

**Comment by ignelias** [comment]
edited it

**Comment by LiquidSmokeBalls** [comment]
kk

**Comment by jumboman32** [comment]
confusing description, uses the template

**Comment by ignelias** [comment]
updates?

**Comment by FluorideHistorian** [comment]
now possible in v2.0
