### ISSUE TITLE
[BUG] strafe speed doesn't work with jump boost

### ISSUE THREAD

**Issue by Mateciotti** [RusherDevelopment/rusherhack-issues#1058]
**Describe the bug**
The speed strafe doesnt work at all when you have speed and jump boost

**To Reproduce**
just try to use strafe with beacons with jumpboost and speed

**Expected behavior**
A fix bc in future client that doesnt happen and i dont want to use future xd

**Comment by jumboman32** [comment]
replicated.

**Comment by FluorideHistorian** [comment]
in what way does it not work
