### ISSUE TITLE
[FEATURE] EntitySpeed TPS Adjustment

### ISSUE THREAD

**Issue by Infisrael** [RusherDevelopment/rusherhack-issues#1070]
**What feature would you like to be added.**
EntitySpeed Auto Audjustment in Certain TPS

**Is your feature request related to a problem? Please describe.**
When I travel in 2b2t, I am getting disconnected due to Low TPS - Therefore I would like an autoadjustmemt into the Entity Speed.

**Additional context**
None.

**Comment by GentlemanMC** [comment]
yez BLEZ john do that

**Comment by jennifer-uwu** [comment]
misclick

**Comment by jennifer-uwu** [comment]
frick

**Comment by Infisrael** [comment]
bump.

**Comment by FluorideHistorian** [comment]
this has been added in the next update
