### ISSUE TITLE
[FEATURE] no item movement

### ISSUE THREAD

**Issue by qanon111** [RusherDevelopment/rusherhack-issues#1084]
**What feature would you like to be added.**
mode for viewmodel which makes it so items stay in place and don't move

**Is your feature request related to a problem? Please describe.**
No

**Additional context**
https://youtu.be/e2Hq1DxrG0M look at his hands

**Comment by LiquidSmokeBalls** [comment]
shawty thats called swing module

**Comment by qanon111** [comment]
look at the video i posted

**Comment by qanon111** [comment]
jfc see how his hands don't move when he moves his camera? thats what i want

**Comment by SoggyBacco** [comment]
viewbob... its in optifine.

**Comment by FluorideHistorian** [comment]
this has been added as the "Sway" setting in v2.0
