### ISSUE TITLE
[FEATURE] custom clickgui backround color and enemy manger window.

### ISSUE THREAD

**Issue by GentlemanMC** [RusherDevelopment/rusherhack-issues#1090]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
1-background color setting to clickgui
2-enemy manger window

**Is your feature request related to a problem? Please describe.**
no
never has been thanks to rusherhack 
**Additional context**
a better idea is to merge both of friend and enemy windows and rename the friend manger button to social manger

**Comment by k15ayk** [comment]
sounds like a really nice idea for the enemy viewer module. Would be extremely helpful to see there statuses and effects. But name tag is still an excellent module for a substitute

**Comment by HarryPotter42MC** [comment]
GentlemanMC do you have anything to do with Abyss? I think I saw you in relation to that this morning

**Comment by John200410** [comment]
The ability to manage enemies via window were added in v2.0 with the Relations window
