### ISSUE TITLE
[FEATURE] ExtraTooltips, item size

### ISSUE THREAD

**Issue by odpay** [RusherDevelopment/rusherhack-issues#1098]
**What feature would you like to be added.**
ExtraTooltips, item size: shows the item size in bytes/kilobytes in the items tooltips when hovering over it

[example from meteor client](https://media.discordapp.net/attachments/875532414259179530/900507793394630706/unknown.png)
**Additional context**
should work with any item including shulkers with shulker preview on, and the inside items whilst hovering over them in shulker preview

**also allow an option to show in raw bytes or simplify to approx kilobyte size**

**Comment by odpay** [comment]
self bump 1 month later

**Comment by John200410** [comment]
This has been added in v2.0
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/43681932/440f8ef8-955f-4986-b09a-0e5e0f907aa4)
