### ISSUE TITLE
[FEATURE] Dinnerbone / Grumm Rendering

### ISSUE THREAD

**Issue by whosthatperson** [RusherDevelopment/rusherhack-issues#1101]
**What feature would you like to be added.**
Dinnerbone. It should make the player turn upside down (client side) and it'll basically just turn your player upside down like when you name a mob dinnerbone
**Is your feature request related to a problem? Please describe.**
It is nothing related to an issue, just a tiny suggestion that would be enjoyable 

**Additional context**
No additional context needed.

**Comment by jumboman32** [comment]
Australia > Players

**Comment by John200410** [comment]
I will probably never add this to rusherhack; This would better be served as a plugin instead
