### ISSUE TITLE
[FEATURE] Auto Fish Module Reel In Method

### ISSUE THREAD

**Issue by eightyninetytwo** [RusherDevelopment/rusherhack-issues#1102]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
_**I would like an addition to the auto fish module, where you can change the different kind of "reel-in" method.**_

**Is your feature request related to a problem? Please describe.**
_**Only problem I have is that when auto fishing in groups, since it relies on sound to reel in, my friends affect when each other reel in, wasting durability on the fishing rod. Not that important, but would be cool if it could be changed.**_

**Additional context**
_**Maybe there's a way to detect when the fishing rod bounces in order to reel in? Or only when it hears the splash of just your fishing rod? Think it'd be cool if you could change the method it uses to reel in.**_

_**EDIT: Also had another idea, maybe you could make a parameter that allows you to change the maximum distance from the player that the sound is heard in order to activate the reel in? Just a thought.**_

**Comment by jumboman32** [comment]
I don't think this possible in 1.12

**Comment by FluorideHistorian** [comment]
autofish has been rewritten in the next update
