### ISSUE TITLE
[FEATURE] Speed Improvements

### ISSUE THREAD

**Issue by synnkfps** [RusherDevelopment/rusherhack-issues#1108]
**What feature would you like to be added.**
A "Speed Height" Option, which will cap the height of your jump, "Speed Cap" Option, which will cap the maximum X and Z speed of your player

**Is your feature request related to a problem? Please describe.**
Some servers have a slower speed cap, so you get rubberbanded if you are above the speed cap value.

**Additional context**
N/A

**Comment by Vaimok** [comment]
you can already change speed of your movement modules.

**Comment by GentlemanMC** [comment]
> you can already change speed of your movement modules.

unblock me or...
💀

**Comment by storm772** [comment]
> 
> 
> you can already change speed of your movement modules.

How? Timer? It's not that easy.

**Comment by SoggyBacco** [comment]
turning on the strict option limits your strafe speed to work om strict servers

**Comment by storm772** [comment]
thats not what i want

**Comment by SoggyBacco** [comment]
> thats not what i want

well it works fine so thats what u get

**Comment by storm772** [comment]
Vanilla sprint + jump is faster than strict

**Comment by Vaimok** [comment]
> Vanilla sprint + jump is faster than strict

untrue! please close this issue and learn how to properly configurate modules.

**Comment by FluorideHistorian** [comment]
closing since 2b patched speed and strict strafe exists

**Comment by FluorideHistorian** [comment]
(might make a custom speed mode someday though)
