### ISSUE TITLE
[FEATURE] Map Downloader

### ISSUE THREAD

**Issue by Sand-Turtle** [RusherDevelopment/rusherhack-issues#1113]
By enabling the module, all map packets sent to the client will be downloaded as a 128x128 png
A detailed explanation of what this feature should be.

**Is your feature request related to a problem? Please describe.**
it would just be nice to have clean screenshots of maps without installing forgehax 🤢

**Additional context**
Not urgent but requested

**Comment by Infisrael** [comment]
based

**Comment by GentlemanMC** [comment]
Halal 👍

**Comment by Lavacasted** [comment]
cool

**Comment by browsky300** [comment]
yes please add this

also john if you add this, could you find a way to make it more consistent? forgehax doesn't download all the maps the first time and kicks you often.

**Comment by John200410** [comment]
This has been added in the next update as the "Cache" setting in ExtraTooltips -> Maps
