### ISSUE TITLE
[BUG] Screen Just Turns Sky Blue When I Load Into A Server

### ISSUE THREAD

**Issue by HausemasterIssue** [RusherDevelopment/rusherhack-issues#1132]
**Describe the bug**
When I boot up RusherHack, with no other mods other than OptiFine and load into a server, the screen just turns completely sky blue in Minecraft. There is no HUD, not even the Minecraft options will show up. However, if I press the GUI key for RusherHack the screen turns black, and if I disable the GUI via a key the screen turns blue again. However, once I load into the game a few times it goes away, but then if I wait a few hours and load it up again, same thing happens.

**To Reproduce**
Wait a few hours without booting up Minecraft, the boot it up with RusherHack and OptiFine installed, and the issue should occur.

**Other mods**
OptiFine

**Expected behavior**
I should be able to see things.

**Screenshots**
![2021-11-15_19 00 55](https://user-images.githubusercontent.com/90464553/141871542-15a5e4be-9a6d-4028-ba4f-a9ae3b72e5cc.png)
_What I see when I load into a server with the RusherHack GUI on, if it is off then the screen is sky blue instead_

**Additional context**
It could be caused because of OptiFine, or maybe just a render feature in RusherHack.

**Comment by John200410** [comment]
This is a bug with ESP Outline mode
