### ISSUE TITLE
[FEATURE] Sprint Improvements

### ISSUE THREAD

**Issue by HausemasterIssue** [RusherDevelopment/rusherhack-issues#1135]
**What feature would you like to be added.**
Just a few simple improvements that should be added to sprint that in general just make it better or make the anti-cheat happier. These include:

- Do not sprint if the player is eating, drinking a potion, using a bow etc.
- Do not sprint if the player is colliding with a block
- No idea how your sprint works but it should press the sprint key when doing it

These things are just little fixes or improvements that would make the sprint better on stricter servers.

**Is your feature request related to a problem? Please describe.**
Can potentially rubberband you on stricter servers if these features are not implemented

**Additional context**
These fixes are like 2 lines of simple code, they are easy to add.

**Comment by FluorideHistorian** [comment]
sprint functions correctly on strict servers as of v2.0
