### ISSUE TITLE
[FEATURE]custom shader command for shaderESP

### ISSUE THREAD

**Issue by GentlemanMC** [RusherDevelopment/rusherhack-issues#1140]
**What feature would you like to be added.**
an option to load custom shaders to shaderESP

**Additional context**
this is an example of it 
https://streamable.com/wm5vog

**Comment by LiquidSmokeBalls** [comment]
I think john might have said he will do it soon but most likely not (Then again I do not know, so I could be wrong about that)

**Comment by GentlemanMC** [comment]
> I think john might have said he will do it soon but most likely not (Then again I do not know, so I could be wrong about that)

he will do it soon
exactly like he did to the targetHUD and the bedAura :trollface:

**Comment by FluorideHistorian** [comment]
duplicate of #927
