### ISSUE TITLE
[FEATURE] ExtraSign Improvements

### ISSUE THREAD

**Issue by wce2005a** [RusherDevelopment/rusherhack-issues#1147]
**What feature would you like to be added.**
Instead of presets of sign dates, EU/US, make it so we can customize the dates so
*signdate %date%, %time% / %ign%
/ for new line
or an alternative verbose, %mon% %day% %year% %24htime% %time% / %currentalias%

**Is your feature request related to a problem? Please describe.**
US/EU Times are mixed, this makes it more clear.

**Additional context**
n/a

**Comment by jumboman32** [comment]
add a title next time pls

**Comment by wce2005a** [comment]
> 

Oops sorry

**Comment by FluorideHistorian** [comment]
duplicate of #819
