### ISSUE TITLE
[FEATURE] AutoSurround but better

### ISSUE THREAD

**Issue by IncognitoModeDev** [RusherDevelopment/rusherhack-issues#1151]
**What feature would you like to be added.**
When on 1.12.2 if they place a crystal one block away from your obsidian that you are on your surround. The surround will mostly fail
so in order to fix that make it so if there is a crystal like near your obsidian that you are surrounded break it because that would help
to reduce your surround failing and your feet from getting exposed and getting crystaled.

If need more info dm me Incognito.js#1690

**Is your feature request related to a problem? Please describe.**
Nope

**Additional context**
Given at the feature above also this feature is inspired by a client called meteor client which is open source and Hope this feature can be added. Thanks :D

**Comment by FluorideHistorian** [comment]
AutoSurround has been rewritten and this has been included as a mode in the AntiCity setting
