### ISSUE TITLE
[FEATURE] TPSSync for FastBreak

### ISSUE THREAD

**Issue by wce2005a** [RusherDevelopment/rusherhack-issues#1169]
**What feature would you like to be added.**
When mining large chunks and if the server is laggy, I wanna move fast but you can't mine as fast. So a setting to sync the mining speed to the TPS would be nice. as if mining with timer tpssync instead.

**Is your feature request related to a problem? Please describe.**
When the server is under ~15tps half the time you will have to mine blocks 2 times if not more, Having it sync with timer would be nice, rather than slowing down movement too.

**Additional context**
In timer, TPSSync Setting only for block breaking
Also, if possible an offset mode, so slow it down by % or a value

**Comment by FluorideHistorian** [comment]
apparently tps synced mining has been added to paper so this isnt required anymore
