### ISSUE TITLE
[BUG] Blink with kill aura will attempt to attack ghost player

### ISSUE THREAD

**Issue by a-a-afk** [RusherDevelopment/rusherhack-issues#1172]
**Describe the bug**
When you toggle blink with kill aura on, the client will attempt to attack the ghost player.

**To Reproduce**
Enable both kill aura and blink

**Other mods**
phosphpor, cookie client, journeymap (This bug happened before I got journeymap and cookie)

**Expected behavior**
Client should not attempt to attack ghost player.

**Additional context**
The only way around this is adding yourself as a friend. But it's just sad to be your own friend.

**Comment by NutrientAphid** [comment]
just add yourself as a friend

**Comment by FluorideHistorian** [comment]
this has been fixed in v2.0
