### ISSUE TITLE
[BUG] AutoTrap Exposed mode not working properly 

### ISSUE THREAD

**Issue by AquaMinerale2b2t** [RusherDevelopment/rusherhack-issues#1181]
AutoTrap in mode exposed doesnt place support blocks. It stops autotrap from completing the trap.
![2021-12-25_13 38 17](https://user-images.githubusercontent.com/96651128/147384082-55173e36-275d-430c-b1ff-db27c3b09e3b.png)

**Comment by John200410** [comment]
Closed in favor of #1435

**Comment by GentlemanMC** [comment]
give me that pack please
