### ISSUE TITLE
[FEATURE] anti pistion push

### ISSUE THREAD

**Issue by Bayon009** [RusherDevelopment/rusherhack-issues#1202]
**What feature would you like to be added.**
a anti pistion push so you cant get pushed out of a holl as easy 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [some nn push me out of a holl and pops me 2 times]

**Additional context**
ik it works bc konass has it and some ather clients to

**Comment by FluorideHistorian** [comment]
Velocity -> Pushing should prevent this

reopen if still happens in v2.0
