### ISSUE TITLE
[FEATURE] HandChams

### ISSUE THREAD

**Issue by adabugra** [RusherDevelopment/rusherhack-issues#1229]
Add hand chams and alsı you can add them to the crystals and items.

![unknown1](https://user-images.githubusercontent.com/57899270/154330928-7e524849-e278-4cd6-8a71-3d895e74c004.png)
![unknown12](https://user-images.githubusercontent.com/57899270/154331029-29f594c5-d779-405f-a863-4fa8a1de70a3.png)

**Comment by Ozynt** [comment]
merged in into issue #43
