### ISSUE TITLE
[FEATURE] baritone with base finder

### ISSUE THREAD

**Issue by terminator-alligator** [RusherDevelopment/rusherhack-issues#1232]
**A detailed explanation of what this feature should be.**

Baritone auto walk under the travel section of base finder
Along with a pause baritone option when a base is found

**Is your feature request related to a problem? Please describe.**

Current options don't offer the same versatility as baritone

**Additional context**

Would probably be incompatible with NewChunkLimit
Lambda client already has this capability

**Comment by FluorideHistorian** [comment]
duplicate of #892
