### ISSUE TITLE
[FEATURE] ScreenshotProtect

### ISSUE THREAD

**Issue by Coop3r** [RusherDevelopment/rusherhack-issues#1248]
ScreenshotProtect Module, when toggled on, and you take a screenshot rusherhack coordinates and direction are removed from the screenshot or blurred.

**Comment by quackitiy** [comment]
hey coopurr, just disable coords before taking screenie :)

**Comment by Doogie13** [comment]
> hey coopurr, just disable coords before taking screenie :)

effort

**Comment by FluorideHistorian** [comment]
duplicate of #378
