### ISSUE TITLE
[FEATURE] Sliding RGB color Setting under Shader ESP

### ISSUE THREAD

**Issue by quackitiy** [RusherDevelopment/rusherhack-issues#1258]
**What feature would you like to be added.**

I'd like to know if it is possible for John to add a setting to ESP that can give off a shader ESP resembling Future Client's "Shader" module.
________
**Is your feature request related to a problem? Please describe.**
This feature request does not relate to any client or real world problems.
________
**Additional context**

Here is a very short video showing the appearance of current rusherhack shader ESP, then Future Client's "Shader" module.
[https://media.discordapp.net/attachments/556977073500192768/952721121092984832/Screen_Recording_2022-03-13_at_7.09.31_PM.mov](url)

It could be implimented by adding a button under the Shader Settings in the ESP module settings. This button would be apply a sliding rgb coloring to ESP with the Shader mode.
________

**Comment by TwoThreeTwo** [comment]
Hi quackitiy,

can you please repost your video? Please host it with GitHub so that way at any point of time our support moderators will be able to see a visual preview of what you want to be added into RusherHack.

Thank you

**Comment by John200410** [comment]
This was already added in v2.0
