### ISSUE TITLE
[BUG] autocrystal target: damage faceplace issue

### ISSUE THREAD

**Issue by SoggyBacco** [RusherDevelopment/rusherhack-issues#1268]
when autocrystal is set to target damage it doesn't ignore mindmg when your target is at your set faceplacehp. 
this isnt a problem with target mode distance/health and target damage does work fine for armorplace so its definitely a bug

**Comment by SoggyBacco** [comment]
also it seems like this only happens when faceplacehp is set under 20

https://user-images.githubusercontent.com/76087383/159383068-34cb62a5-a2d5-4a51-9577-b84e7680ff6c.mp4

pretty annoying considering any faceplace above 12hp is a huge waste

**Comment by Mathrandom7910** [comment]
yes

**Comment by FluorideHistorian** [comment]
reopen if still happening with the new AutoCrystal
