### ISSUE TITLE
[FEATURE] "uwu" mode for Rusherhack FancyChat module

### ISSUE THREAD

**Issue by REALERvolker1** [RusherDevelopment/rusherhack-issues#1270]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
"uwu" mode fow Wushewhack `FancyChat` moduwe.
-- Weasons to add--
```
- Makes wawping on 2b2t much mowe enjoyabwe
- Impwuvs intwapewsonyaw wewationships on anyawchy sewvews
- Weads to bettew gwoup dipwomacy
- Awwows fow gweatew wawping potentiaw, especiawwy fow chatfags and wewated wawpews
- Wiww impwuv the genyewaw heawth and weww-being of the 2b2t pwayewbase
- Awweviates stwess and anxiety showt-tewm, and has wong tewm benyefits wike weduced awzheimew's wisk.
```

Thank you fow youw considewation. Have a nyice day. UwU
**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by system69-e** [comment]
no

**Comment by system69-e** [comment]
![image](https://user-images.githubusercontent.com/67830794/160063270-f8c5a203-fdb2-48a4-be65-63df7ff043a9.png)

**Comment by HausemasterIssue** [comment]
This one deserves the tr🤡ll category.

**Comment by rolkoztm** [comment]
Yes please

**Comment by Doogie13** [comment]
this would actually be a good addition to a basically meaningless module for more novelty

**Comment by rolkoztm** [comment]
yes

**Comment by system69-e** [comment]
> This one deserves the tr🤡ll category.

seconding this

**Comment by FartCheese** [comment]
...wtf?

**Comment by FartCheese** [comment]
> This one deserves the tr🤡ll category.

this

**Comment by Doogie13** [comment]
And fancychat isnt a troll module already? we nweeeeed thwis fwow wusherhack

**Comment by storm772** [comment]
cringe and edgy

**Comment by FluorideHistorian** [comment]
this has been added in v2.0
