### ISSUE TITLE
[FEATURE] Speed modes

### ISSUE THREAD

**Issue by Doogie13** [RusherDevelopment/rusherhack-issues#1272]
**What feature would you like to be added.**

A few extra settings to speed under "LowHop"
Lowhop modes:
Zero (sets Y motion to 0 part way through jump)
Floor (sets Y motion to -6969 part way through jump)
and a slider to change where this is in the jump (ticks in air)
These would be fairly easy to add as an option in Strafe to LowHop 

Also a speed slider in Strafe for less strict servers

**Is your feature request related to a problem? Please describe.**
Customisability is fun

**Additional context**
LowHop works on normal NCP but not on Updated NCP
You can get a pseudo LowHop when combining Future and RH speed at once, it will pull you to the ground at the peak of your jump (which does bypass NCP, hence this suggestion), also YPort is essentially lowhop which sucks you to the ground after 1 tick which also bypasses, and onground is (sort of) silent YPort

**Comment by HausemasterIssue** [comment]
Also add BHop with a controllable speed limit, it works on some servers if the speed limit is low enough.

**Comment by TwoThreeTwo** [comment]
Why not just work on rusherhack doogie?

**Comment by FluorideHistorian** [comment]
>LowHop works on normal NCP but not on Updated NCP
