### ISSUE TITLE
[FEATURE] "pvp" options entitylist (totempops)

### ISSUE THREAD

**Issue by cherosin** [RusherDevelopment/rusherhack-issues#1273]
adding "pvp" options on entitylist such as popcounter and hp
and make it so u can turn off distance

**Comment by TwoThreeTwo** [comment]
You mean pvp info in Combat?

**Comment by TwoThreeTwo** [comment]
![image](https://user-images.githubusercontent.com/83801755/161464595-ee31ebca-ea55-42ec-a4bf-15c095b1f3f7.png)

**Comment by HausemasterIssue** [comment]
I believe cheroso means something like this:

![image](https://user-images.githubusercontent.com/90464553/161549449-b949a73a-5d56-472c-85b5-6673e34e2a4f.png)

**Comment by TwoThreeTwo** [comment]
> I believe cheroso means something like this:
> 
> ![image](https://user-images.githubusercontent.com/90464553/161549449-b949a73a-5d56-472c-85b5-6673e34e2a4f.png)

ah, didn't realize that ig

**Comment by FluorideHistorian** [comment]
this is now possible as of v2.0
