### ISSUE TITLE
[BUG] Left line in csgo crosshair dynamic after dynamic is closed

### ISSUE THREAD

**Issue by Papa-Quill** [RusherDevelopment/rusherhack-issues#1279]
**Describe the bug**
Left line of csgo crosshair is dynamic even when dynamic is disabled

**To Reproduce**
https://cdn.discordapp.com/attachments/590973415351910426/962812551266173018/unknown.png

**Other mods**
Future

**Expected behavior**
It doesn't try to be dynamic when disabled

**Screenshots**
[video](https://cdn.discordapp.com/attachments/590973415351910426/962812134306218054/crosshair_thing.mp4)

**Comment by John200410** [comment]
Closed in favor of #1410
