### ISSUE TITLE
[FEATURE] PacketLogger toString Serializing Improvements

### ISSUE THREAD

**Issue by rfresh2** [RusherDevelopment/rusherhack-issues#1286]
**What feature would you like to be added.**
The PacketLogger should log actual data in more packets where it currently only logs Java object hashes.

**Is your feature request related to a problem? Please describe.**
When I use the PacketLogger feature, not all built-in minecraft classes implement the `toString` method and only get their object hash logged. This means those classes use the default `toString` implementation for `Object`. It should be possible to implement a proper `toString` via mixins or your own wrapper on the logger with specific behavior for specific classes being logged.

**Additional context**
Example attached for SPacketEntityMetadata and SPacketDestroyEntities. EntityDataManager.DataEntry object values can be multiple types like int, boolean, float, etc.

Example of `toString` in MCProtocolLib: https://github.com/GeyserMC/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/game/entity/metadata/EntityMetadata.java#L53-L56

![2022-04-17_15 28 08](https://user-images.githubusercontent.com/89827146/163734563-4b53dc06-6bb1-4a9a-9107-783c9d29a035.png)

**Comment by Signam** [comment]
Wow this guy is smart, he should consider making a tool to find minecraft servers to blow up and join a group with a cool name like the 6th column or something like that idk just putting it out there

**Comment by John200410** [comment]
This should be fixed in the next update. PacketLogger has been greatly improved
