### ISSUE TITLE
[FEATURE] ItemSaver option in AutoTunnel

### ISSUE THREAD

**Issue by hashalite** [RusherDevelopment/rusherhack-issues#1290]
**What feature would you like to be added.**
An option in AutoTunnel that pauses mining when pickaxe durability reaches a specified value.

**Is your feature request related to a problem? Please describe.**
AutoTunnel breaks your pickaxe if left afk

**Comment by hashalite** [comment]
AutoMine could also benefit from this

**Comment by HausemasterIssue** [comment]
Yes, it should also send a notification on Windows or in game so if you are tabbed out you will know when to grab another or repair your pickaxe.

**Comment by FluorideHistorian** [comment]
use AutoTool
