### ISSUE TITLE
[BUG] Soul Sand scaffold

### ISSUE THREAD

**Issue by a-a-afk** [RusherDevelopment/rusherhack-issues#1292]
**Describe the bug**
When scaffold is on and ur walking on soul sand, it places blocks beneath the soul sand instead of to the side.

**To Reproduce**
enable scaffold with/on soul sand

**Other mods**
none

**Expected behavior**
It should not place beneath the soul sand block, but to the appropriate side.

**Comment by HausemasterIssue** [comment]
Yes, I have noticed RusherHack scaffold can place under blocks when you are on something like a fence or gate, it can flag the AntiCheat sometimes.

**Comment by TwoThreeTwo** [comment]
yeah this is with anything that has a small hit box / normal hit box but blocks going out of it. Been like this for a while ig

**Comment by FluorideHistorian** [comment]
this has been fixed in v2.0
