### ISSUE TITLE
[FEATURE] 1.18 New Chunks System

### ISSUE THREAD

**Issue by Qualet** [RusherDevelopment/rusherhack-issues#1299]
**This module will be used only on 2b2t 1.18 to search for stash/base**
The module will compare the old 1.12 chunks with the new 1.18 chunks

**How will he be**
1. Seed overlay compares the chunk from 40 to 90 height
2. if no matches are found, then the chunk is highlighted in red
3. if the new chunk is loaded more than 2 times, the color changes to yellow

Seed overlay found a new chunk on test.2b2t.org

![Untitled-1_copy](https://user-images.githubusercontent.com/103982168/167383920-ba2a52be-1891-433f-b9e7-7c48a3aa1717.png)

https://cdn.discordapp.com/attachments/936485813154349166/972982899466981456/Untitled-1_copy.png

**Comment by Qualet** [comment]
Fck

**Comment by Qualet** [comment]
> **This module will be used only on 2b2t 1.18 to search for stash/base** The module will compare the old 1.12 chunks with the new 1.18 chunks
> 
> **How will he be**
> 
> 1. Seed overlay compares the chunk from 40 to 90 height
> 2. if no matches are found, then the chunk is highlighted in red
> 3. if the new chunk is loaded more than 2 times, the color changes to yellow
> 
> Seed overlay found a new chunk on test.2b2t.org
> 
> ![Untitled-1_copy](https://user-images.githubusercontent.com/103982168/167383920-ba2a52be-1891-433f-b9e7-7c48a3aa1717.png)
> 
> https://cdn.discordapp.com/attachments/936485813154349166/972982899466981456/Untitled-1_copy.png

**Comment by HausemasterIssue** [comment]
Nice image, but no skill :(

**Comment by Mathrandom7910** [comment]
> Nice image, but no skill :(

No lol.

Also I like "Idea by Qualet", like u want to be remembered for this game changing idea that will be shown by fit. This is an awful idea that wouldn't work.

**Comment by GentlemanMC** [comment]
Genartaion bypass

**Comment by FluorideHistorian** [comment]
added in v2.0
