### ISSUE TITLE
[FEATURE] Hotbar Swap 

### ISSUE THREAD

**Issue by ghost** [RusherDevelopment/rusherhack-issues#1303]
What feature would you like to be added.

I would like to see a module called hotbar swap (pvp/utility module) added to the client. It allows for a keybind to be set and when the bind is pressed it will swap your hotbar and bottom row around so that you can easily use extra tools and items without having to rearrange your hotbar in pvp or even just generally playing. 

Thanks for taking the time to read my suggestion.

**Comment by John200410** [comment]
I don't exactly understand but I think this AutoTool is what you were asking for
