### ISSUE TITLE
[FEATURE] Totem while elytraflying

### ISSUE THREAD

**Issue by 2u9** [RusherDevelopment/rusherhack-issues#1309]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.
Offhand automatically switches to totem, when elytra is opened.

**Is your feature request related to a problem? Please describe.**
I think, it would be nice to have some kind of this setting, so you don't have to manually switch to totem every time you are going to fly with elytra while using offhandcrystal.

**Additional context**

**Comment by FluorideHistorian** [comment]
Added in v2.0
