### ISSUE TITLE
[FEATURE] buncha features i'd like

### ISSUE THREAD

**Issue by 06d** [RusherDevelopment/rusherhack-issues#1334]
time limit for blink (would be really nice to have it since timing it is pain
(if press up arrow it goes back to your previous command) thing in console
maybe a setting that pulls up the windows while your in chat (if possible)
popchams (smexy)
ignore list for regear (ignores certain items, since making a whole-ass new kit just because you want to regear while having an extra item like a bow aint really nice)

**Comment by TwoThreeTwo** [comment]
John has said that he be adding popchams

**Comment by TwoThreeTwo** [comment]
updated comment because I fucked up the wording

**Comment by TwoThreeTwo** [comment]
There's also a opened issue about blink time limit #755

**Comment by TwoThreeTwo** [comment]
John has added time limit for blink in the new plus update.

**Comment by FluorideHistorian** [comment]
one suggestion per git issue please
