### ISSUE TITLE
[FEATURE] color setting for client chat notifications

### ISSUE THREAD

**Issue by ILuvDix** [RusherDevelopment/rusherhack-issues#1343]
**What feature would you like to be added.**
I would like to be able to change the color of the client notifications in chat. Right now itš only possible to change the color of the [RUSHERHACK] label. This would make the notifications more "visible" in chat.

**Additional context**
![image](https://user-images.githubusercontent.com/71260967/184236443-85f454f3-5f54-4d5a-852f-016b67ef40a2.png)
I would like to be able to change the color of these client messages.

**Comment by FluorideHistorian** [comment]
related to #1123

**Comment by FluorideHistorian** [comment]
oh yeah i added this a bit ago
