### ISSUE TITLE
[FEATURE] Just a bit of stuff that could get improvement 

### ISSUE THREAD

**Issue by Moppl** [RusherDevelopment/rusherhack-issues#1345]
AutoTrap - Not placing support blocks to block people in
AntiAfk - Moves freecam instead of player (even with freecam mode new)
Quiver - Swap back to old slot option
Step - Separate upwards/downwards height setting
Swing - Swingspeed option (looks hot)
Fastbreak - Silent Packet break / Queue mode for mode packet (mark multiple blocks to be mined)
Autotool - Silent Swap

**Comment by FluorideHistorian** [comment]
one suggestion per issue please
