### ISSUE TITLE
[BUG] Issue with RusherHack account manager

### ISSUE THREAD

**Issue by bstar16** [RusherDevelopment/rusherhack-issues#1358]
**Describe the bug**
If i launch my game and then change my account without logging in my game freezes when i join a server, i have to join a server and then change my account for it not to freeze

**To Reproduce**
launch game then login to different alt and join a server

**Comment by TwoThreeTwo** [comment]
Please link your discord account in the installer and join the RusherHack discord to receive support.

**Comment by TwoThreeTwo** [comment]
sorry lol

**Comment by FluorideHistorian** [comment]
does this still happen

**Comment by bstar16** [comment]
afaik not sure but i think it was still happening on 1.12, was also random never consistent so could never determine actual cause of it. i know it's rusher tho because removed everything still happened

**Comment by FluorideHistorian** [comment]
i will close this when account manager is ported to v2.0
