### ISSUE TITLE
[BUG] A bug regarding fakeplayer in wich you delete yourself.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1359]
**Describe the bug**
When using *fakeplayer del (your player name), you delete yourself instead of the fakeplayer, (There doesn't have to be a fakeplayer for you to be deleted.)

**To Reproduce**
Use *fakeplayer del (your player name).

.**Other mods**
none

**Expected behavior**
Having it remove the fakeplayer that's named after your player name or do nothing when there isn't an fakeplayer with your name, without it removing you, as it currently does in both circumstances.

**Screenshots**
none

**Additional context**
none

**Comment by Mathrandom7910** [comment]
no dont patch this
