### ISSUE TITLE
[FEATURE] Give certain people a certain colored tracer and esp.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1361]
**What feature would you like to be added.**
An option to give certain people a differently colored tracer and esp, just like you have with friends, preferably using the windows gui thing.

**Is your feature request related to a problem? Please describe.**
Nope, just a nice feature to have.

**Additional context**
This would be really usefull when you want to mark certain people, like when you'd want to mark 4 different teams, and that kind of stuff, ofcourse it'd work kind of like the friends list, but instead of just adding a name, you add a name and a color.

**Comment by John200410** [comment]
You can already customize the friend/enemy colors
