### ISSUE TITLE
[BUG] Carpets broken with scaffold

### ISSUE THREAD

**Issue by ItzDawnfall** [RusherDevelopment/rusherhack-issues#1362]
**Describe the bug**
You can no longer place carpets using scaffold

**To Reproduce**
put carpet in hotbar, go up a block, and start walking
supposed to work on ocean as well

**Comment by Mathrandom7910** [comment]
Is it in your white/blacklist

**Comment by FluorideHistorian** [comment]
This has been fixed as of v2.0
