### ISSUE TITLE
[BUG] Entity ESP continually tries to trace the entity if you pause in singleplayer while falling

### ISSUE THREAD

**Issue by CozyMeli-gitv2** [RusherDevelopment/rusherhack-issues#1364]
**Describe the bug**
If you are in singleplayer, and are in the process of falling, with esp on for entities, and pause the game by pressing ESC, the ESP will continually try to move with you to the future position of the entity based on your camera angle, even while paused. This runs in the backround, and is visually annoying, and uses system resources.

**To Reproduce**
Open singleplayer > Look at entities with ESP and entities enabled > Move foward and jump > Pause the game while falling > See entity ESP try to move to the future position, but as the game is paused, it just continually flickers.

 Applies to all ESP modes, however most viewable with CSGO or Shader.

**Other mods**
Occurs with rusherhack as the sole mod.

**Expected behavior**
Expected to stop predicting the entity's future position, and continually try to move to it, when the game is paused. This is an unnecessary process when paused, as it just results in flickering, and unnecessary resources wasted. You can see expected behavior by pausing the game while standing still, you can see no flickering or movement occurs, it just stands still, as nothing is moving for it to need to move with.

**Screenshots**
Cannot fit a moving effect into a screenshot, but it is very easy to reproduce. 

**Additional context**
No additional context.

**Comment by TwoThreeTwo** [comment]
Not an issue with outline or shader, mostly just Box and CSGO. 

> Not an issue with outline or shader
Testing it with Outline froze the mobs pos like it should without any rendering issues. Testing it with Shader is the same thing.

I think this is done because since it's not rendering the actual entities position and just rendering outside of it could be the issue

**Comment by CozyMeli-gitv2** [comment]
No this occurs with outline and shader. You need to gain specific momentum, so it is pretty difficult to reproduce at first, until you get the hang of it. It happens with all modes, your luck varies so you may notice it on some and not others.

**Comment by TwoThreeTwo** [comment]
Oh alright

**Comment by John200410** [comment]
Can you provide a video of this happening to Outline and Shader mode?

**Comment by CozyMeli-gitv2** [comment]
> Can you provide a video of this happening to Outline and Shader mode?
Sure! I will start recording it now, stay on hold for about 2 minutes.

**Comment by CozyMeli-gitv2** [comment]
Was unable to reproduce on outline only, for whatever mindblowing reason. I swear I managed to reproduce that at an earlier date, but ig it fixed itself?? 
Here is the link for it occuring on all modes, other than outline. https://www.veed.io/view/aab9c4c3-653e-4784-aef2-dbd1e461014b/showcase?sharingWidget=true

**Comment by FluorideHistorian** [comment]
seems to be fixed in v2.0, reopen if not
