### ISSUE TITLE
[FEATURE] Shulker auto filler

### ISSUE THREAD

**Issue by Sp1nkelcoding** [RusherDevelopment/rusherhack-issues#1365]
**What feature would you like to be added.**
So like that it will puts items in the shulker at the place what u want but then auto so u can fill your shulkerbox very fast

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by Mathrandom7910** [comment]
cheststealer

**Comment by ShaderTheBlackKid** [comment]
useless feature, besides, you can accomplish this with regear and extrachest by moving the items from chests or shulkers to certain spots in your inventory, disabling regear and enabling extrachest
