### ISSUE TITLE
[BUG] TabGUI Issues.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1371]
**What feature would you like to be added.**
When TabGUI position goes off screen other than left pos, it will not rotate and when opened the settings will go offscreen
![image](https://user-images.githubusercontent.com/83801755/193386644-7c19a983-3e4c-4107-8d9d-1a04555f94a9.png)
![image](https://user-images.githubusercontent.com/83801755/193386646-2f98a25f-6763-4ae7-8083-0708747d92db.png)

When TabGUI settings are opened the category text for miscellaneous goes off screen and extra modules go off screen dont render inside box no matter what height is changed. Only done when not using Custom Font. 
![image](https://user-images.githubusercontent.com/83801755/193386755-ea05ee5d-5b13-440d-b004-8ca50532385c.png)

**Comment by TwoThreeTwo** [comment]
Updated the issues with some issues that I discovered.

**Comment by browsky300** [comment]
John said he won't fix the first one

**Comment by FluorideHistorian** [comment]
current tabgui wont be ported to v2.0
