### ISSUE TITLE
[BUG] ExtraChat Animations select middle click thing going into the rest of the clickgui.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1372]
**Describe the bug**
The dropdown from the Animation from ExtraChat opens into the other module buttom, meaning it just open but the clickgui list doesn't open, it just drops down into the other buttons.

**To Reproduce**
When you use the middle click dropdown on a module it open a list at the bottom to select something from, do that with the ExtraChat Animation setting.

**Other mods**
Optifine 1.12.2 newest version, but I don't think this can be caused by optifine.

**Expected behavior**
To just open a space in the clickgui and not have it open into the modules.

**Screenshots**
I don't know how to but I think I explained it well enough.

**Additional context**
Yes, I think it may be caused by the fact that it is also openable with right click for different setting, and that it doesn't work becouse of that, but that's just speculation, as I currently do now know other settings that have this to test my speculation.

**Comment by VoidBite1** [comment]
My speculation was correct, because it also happens with BowSpam>BowBomb and Nametags>Extensions>Items>Enchants.

**Comment by VoidBite1** [comment]
(This also means that the ... is inside the text saying what its currently on, for example having the ... mixed with the off.)

**Comment by FluorideHistorian** [comment]
i dont understand can you post a screenshot or a video

**Comment by FluorideHistorian** [comment]
well i am unable to reproduce any issues related to this in v2.0, reopen if still occurring
