### ISSUE TITLE
[BUG] Clamping removing things wrongly from the list.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1376]
**Describe the bug**
When you have clamping enabled, and have a list at the bottom of the screen, it adds things properly on the top, but removed them on the bottom, meaning your hud elements will start flying

**To Reproduce**
Just enable clamping in hud and put a list at the bottom, like binds, make it so that the list has some things, then remove them from the list.

**Other mods**
Yea, newest optifine, but I don't think that's the problem.

**Expected behavior**
Having it remove modules from the top instead of the bottom.

**Screenshots**
I think I explained it well enough and I don't exactly know how to add screenshots.

**Additional context**
nope

**Comment by FluorideHistorian** [comment]
this has been fixed as of v2.0
