### ISSUE TITLE
[FEATURE] Enemy color for esp and nametags.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1377]
**What feature would you like to be added.**
Having the enemy color for esp and nametags and other modules with color for players.

**Is your feature request related to a problem? Please describe.**
nope

**Additional context**
Yea, we have an enemy function, but currently its a bit useless.

**Comment by FluorideHistorian** [comment]
this is now possible as of v2.0 using the Colors module
