### ISSUE TITLE
[FEATURE] Having an attack enemy only for Aura and AutoCrystal.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1378]
**What feature would you like to be added.**
I want there to be an enemy only option for the combat modules, we have prefer enemy for some, but not only enemy.

**Is your feature request related to a problem? Please describe.**
nope

**Additional context**
Yea, the enemy option is currently a bit useless.

**Comment by FluorideHistorian** [comment]
this has been added in v2.0
