### ISSUE TITLE
[FEATURE] Having the outline for City Esp go over all 12 lines, other then 4.

### ISSUE THREAD

**Issue by VoidBite1** [RusherDevelopment/rusherhack-issues#1380]
**What feature would you like to be added.**
So you get a full outline with fill on the block.

**Is your feature request related to a problem? Please describe.**
nope

**Additional context**
Yea, it'll make the City Esp better.

**Comment by FluorideHistorian** [comment]
what

**Comment by VoidBite1** [comment]
I don't really remember what I meant, I've forgotten what City Esp is, so I can't really check either, it has something to do with the visuals though.

**Comment by FluorideHistorian** [comment]
💀

**Comment by FluorideHistorian** [comment]
i think its an esp for peoples surround blocks

**Comment by FluorideHistorian** [comment]
oh i understand what you mean now
![2023-09-13_09 00 09](https://github.com/RusherDevelopment/rusherhack-issues/assets/68972754/6f79f928-b075-45ce-9aab-4735661146df)

**Comment by FluorideHistorian** [comment]
well this was fixed in v2.0
