### ISSUE TITLE
[FEATURE] Chat mirror via a Discord webhook

### ISSUE THREAD

**Issue by CozyMeli-gitv2** [RusherDevelopment/rusherhack-issues#1384]
**What feature would you like to be added.**
A feature similar to Lambda's Chat Plus plugin where all of chat, and when you leave and join a server gets mirrored via a discord webhook. Featuring pings when you leave and join servers, logging all chat to that webhook, and your queue position. This is a highly useful feature I use on lambda, and would absolutely LOVE to see on rusher. 

https://github.com/lambda-plugins/ChatPlus
The chat plus discord notifs module reflects all of this, and you can use it as a reference for what features I am requesting. While rusher does not have plugin support, this is such a module/extra feature under chat that I think deserves to be integrated. 

**Is your feature request related to a problem? Please describe.**
No, no a problem, rather a feature.

**Additional context**
None to be had, I just wish this was a rusherhack feature, as the moment I have to stop using other mods along rusher, is a day I can die happy :3

**Comment by Mathrandom7910** [comment]
I dont understand the purpose of something like this

**Comment by catgirljenni** [comment]
🤓
