### ISSUE TITLE
[FEATURE] Filter bindlist to only show active binds

### ISSUE THREAD

**Issue by 8920420** [RusherDevelopment/rusherhack-issues#1387]
**What feature would you like to be added.**
The ability to click the "Disabled" or "Enabled" box in the bindlist HUD settings and filter for only enabled binds. 

**Is your feature request related to a problem? Please describe.**
Seeing all the inactive binds takes up unnecessary space so being able to filter for only active ones would be useful and would require no extra gui buttons to do. 

**Additional context**
None

**Comment by FluorideHistorian** [comment]
this has been added in the next update
