### ISSUE TITLE
[BUG] Echest caching doesn't work if echest name is modified by a resourcepack

### ISSUE THREAD

**Issue by hashalite** [RusherDevelopment/rusherhack-issues#1388]
**Describe the bug**
If you are using a resourcepack that modifies enderchests' names, echest tooltips doesn't cache their contents.

**To Reproduce**
1. Install a resourcepack that changes the name of enderchests (for example [this one](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode))
2. Enable ExtraTooltips > EnderChests
3. Open your enderchest and move items around
4. Close enderchest and look at tooltip
5. Item positions do not update in the tooltip

**Other mods**
none

**Comment by John200410** [comment]
This should be fixed in rusherhack v2.0
