### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hacker-okan** [RusherDevelopment/rusherhack-issues#1391]
**Describe the bug**
When you eat, speed would not worked
**To Reproduce**
I dont know what is this

**Other mods**
None

**Expected behavior**
Fixed

**Screenshots**
I need video to show

**Additional context**
Try speed while eating and going backwards, you'll see

Ilgaz#7360

**Comment by FluorideHistorian** [comment]
use NoSlow Items
