### ISSUE TITLE
[BUG] Crosshair extends in one direction while moving.

### ISSUE THREAD

**Issue by Minihercules317** [RusherDevelopment/rusherhack-issues#1410]
**Describe the bug**

When using the crosshair module the left line of it extends when moving without dynamic on.

**To Reproduce**

Turn on csgo mode with dynamic and outline off, other settings don't change it.

**Other mods**
List other forge mods you are using (if any):

None.

**Expected behavior**

The crosshair renders and stays static.

**Screenshots**

https://imgur.com/YmIrEos

https://imgur.com/qW1jQTr

**Additional context**

**Comment by John200410** [comment]
This has been fixed in the next update.
