### ISSUE TITLE
[BUG] with shematica

### ISSUE THREAD

**Issue by Pbg4444** [RusherDevelopment/rusherhack-issues#1415]
**Describe the bug**
Nametags and search render at the wrong place when a schematic is loaded
**To Reproduce**
Load a schematic with schematica

**Other mods**
schematica

**Expected behavior**
nametags and search render normally

**Screenshots**
![2023-01-15_11 30 31](https://user-images.githubusercontent.com/116279167/212535729-495672e8-53c5-4ece-82f7-3e747b1acb47.png) when a schematic loaded
![2023-01-15_11 30 35](https://user-images.githubusercontent.com/116279167/212535732-8b11fbb5-7a5a-445a-a06e-d5082c0d5f82.png)
![2023-01-15_11 30 42](https://user-images.githubusercontent.com/116279167/212535734-93180233-e31b-4f48-91cb-78a0b5e7b02d.png)
![2023-01-15_11 30 56](https://user-images.githubusercontent.com/116279167/212535739-fb241b7f-1c41-4ebd-aae6-d40723a68321.png) when a schematic loaded

**Comment by John200410** [comment]
This is due to how schematic renders everything. I have tried looking into this before with no solution.
