### ISSUE TITLE
[BUG] StashSorter crash

### ISSUE THREAD

**Issue by xyzbtw** [RusherDevelopment/rusherhack-issues#1417]
**Describe the bug**
Crashes during usage

**To Reproduce**
Set your pull and sort chests, make sure that they are separated with a wall with tunnels for baritone

**Other mods**
List other forge mods you are using (if any):
AltManager
**Expected behavior**
Expected stashsorter to not crash
**Screenshots**

**Additional context**
Last time it crashed was when baritone didn't go to the correct place and tried opening a chest from 2 far away.
[stashsorter crash january 24 2023.txt](https://github.com/RusherDevelopment/rusherhack-issues/files/10502618/stashsorter.crash.january.24.2023.txt)

**Comment by xyzbtw** [comment]
Crash report is the txt

**Comment by John200410** [comment]
Fixed in the next update
