### ISSUE TITLE
[BUG] Flight does not reset speed on disable

### ISSUE THREAD

**Issue by EBSmash** [RusherDevelopment/rusherhack-issues#1418]
**Describe the bug**
Flight used to speed up in creative does not set attributes back.

**To Reproduce**
Go into a creative world
Turn on flight with speed different than 1
fly around
disable flight
fly around, same speed.

**Other mods**
N/A

**Expected behavior**
it should set the flight speed to default on disabled

**Additional context**
Only occurs in creative

**Comment by John200410** [comment]
This has been fixed in v2.0
