### ISSUE TITLE
[BUG] AutoSorter Content mode not working

### ISSUE THREAD

**Issue by Fishy38** [RusherDevelopment/rusherhack-issues#1423]
**Describe the bug**
When using the auto sorter module if you select the sortmode to be content nothing happens. 

**To Reproduce**
Turn on auto sorter select content as the sort made select a few pull chests and some put chests then click active to enable auto sorter. Nothing happens.

**Other mods**
I tried it with just future and had the same problem but i have lambda. future, rusher hack and optifine

**Expected behavior**
For an example, if i open the put chest and put a shulker of gaps in it and then I select pull chests which have different colored shulkers and different names but still match the same contents of the shulker in the put chest and then activate the module it should start moving all the shulkers that match the same contents of the put chest into the put chest. 

**Additional context**
Any questions about reproducing the problem please message me here YoFishIsCool#9835

**Comment by John200410** [comment]
Fixed in next update
