### ISSUE TITLE
[FEATURE] Quiver Enhancements

### ISSUE THREAD

**Issue by AlphaxHax** [RusherDevelopment/rusherhack-issues#1424]
1. I think that it would be very helpful to have quiver work with people you have friended, because I keep shooting them with harming when trying to buff them.

2. It would also be very helpful to have bow aimbot and bow spam to deactivate temporary when using quiver and looking directly up or at a friended player.

Im always finding it annoying that I cannot use bow aimbot and quiver at the same time. And that quiver will shoot my friends with harming instead of good arrows.

**Comment by FluorideHistorian** [comment]
i added an others setting to quiver but it isn't very good and it's not very feasible to make it good due to arrow travel time

same for bowaimbot and bowspam, you should probably just have those bound
