### ISSUE TITLE
[BUG] "Client" tab does not appear in ClickGUI

### ISSUE THREAD

**Issue by WrityGD** [RusherDevelopment/rusherhack-issues#1429]
![2023-03-07_11 31 31](https://user-images.githubusercontent.com/118527005/223368315-bf2b0561-2319-4916-9587-d125892a3e24.png)

**Comment by Darker-Ink** [comment]
Hey, This github is not for Support, You should instead join the [Discord server](https://discord.com/invite/nvcCyVKuWy) to get support

**Comment by WrityGD** [comment]
ill reopen

**Comment by GentlemanMC** [comment]
try doing *clickgui scale 0.5
