### ISSUE TITLE
[BUG] Theres no "Client" tab in ClickGUI

### ISSUE THREAD

**Issue by WrityGD** [RusherDevelopment/rusherhack-issues#1430]
**Describe the bug**
i dont see "client" in clickGUI
**To Reproduce**
open clickGUI
**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**
![2023-03-07_11 31 31](https://user-images.githubusercontent.com/118527005/223502881-d7c40903-2344-401e-b7e3-8fd38ccaf88d.png)
if applicable, add screenshots to help explain your problem.

**Additional context**

**Comment by John200410** [comment]
This is not a bug. Lower your clickgui's scale to 0.8 by using the "*clickgui scale 0.8" command.

In the future please ask for support in the Discord server, not the Github issue tracker.

**Comment by WrityGD** [comment]
thanks
