### ISSUE TITLE
[BUG] EXPfast module bug

### ISSUE THREAD

**Issue by kazubon12** [RusherDevelopment/rusherhack-issues#1431]
**Describe the bug**
When the EXPfast module's pitch setting is turned on, the head turns down when right-clicking any item.
(When eating food, drawing the bow, placing blocks, etc.)

**To Reproduce**
1.EXPfast turned on
2.pitch setting turned on
3.Right-click while holding some item.

**Expected behavior**
Only look down when holding an XP bottle in mainhand

**Screenshots**
https://streamable.com/23vrqg

**Comment by FluorideHistorian** [comment]
appears to be fixed in v2.0
