### ISSUE TITLE
[FEATURE] Config module overwrite feature 

### ISSUE THREAD

**Issue by Zamplex** [RusherDevelopment/rusherhack-issues#1432]
**What feature would you like to be added.**
There would be nice if you could overwrite saved module profiles when you are doing a lot of changes and dont want to make a new one and delete the old profile all the time.

**Is your feature request related to a problem? Please describe.**
Its not related to a problem

**Additional context**
<img width="226" alt="Screenshot 2023-03-26 151208" src="https://user-images.githubusercontent.com/73429097/227777999-aaf2c89f-4b34-4abf-80ac-db1e59058d69.png">
i think you can see what i mean xD

**Comment by John200410** [comment]
All edits you make to your config will already save to your profile.
