### ISSUE TITLE
[FEATURE] Anti Effect (render)

### ISSUE THREAD

**Issue by JoxxHonor** [RusherDevelopment/rusherhack-issues#1434]
**What feature would you like to be added.**
Anti Effect (render), will remove the change of fov after receiving speed effect for example

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
If im in pvp and somebody speed arrows me and i sprint my view just goes upside down and its not playable like this, i have seen this feature in abyss client and would love to have this client on rusherhack.

Thanks for reading.

**Comment by AquaMinerale2b2t** [comment]
disable dynamic fov on optifine.

**Comment by catgirljenni** [comment]
optifine feature
