### ISSUE TITLE
Setting To Allow Modules To Interact With Each Other [FEATURE]

### ISSUE THREAD

**Issue by Absurv69** [RusherDevelopment/rusherhack-issues#1437]
I think you should add a setting were a user can make modules activate/deactivate by either toggling on or off other modules.
This feature would be pretty simple and an example of this is as follows, i activate crystal aura then flight turns off. This is a pretty simple feature but i think it would help the client out a lot, i have to admit plenty of times i have accidentally had an unwanted/module that collides with others on when i activated another one.

This feature is not related to a problem. This way of modules toggling on/off upon another module being toggled off can simply be done by binding both to the same key and either toggling one on or off before you start using them e.g. i bind step and speed to the same key and then toggle speed of and leave step on, notice how pressing the key switches between the two modules? this was of achieving this is certainly not reliable, depending on computer speed and other factors you could be left in the dust and plenty of times you can accidentally toggle the unwanted module on or even both on if you are using a bind that you press frequently (like speed).

**Comment by FluorideHistorian** [comment]
you can use macros to just have keys toggle off modules only

**Comment by Absurv69** [comment]
> you can use macros to just have keys toggle off modules only

Its always going to have a risk of not working as intended when you are using it frequently, the most reliable way would be to have it built into the client instead of using some macros that are not specifically intended for the purpose if you get what i mean.

**Comment by FluorideHistorian** [comment]
i dont see how it could randomly break

**Comment by Absurv69** [comment]
> i dont see how it could randomly break

Do you mean that there is a setting in macros that allows you to make them only function as toggle offs?

**Comment by FluorideHistorian** [comment]
yes

**Comment by Absurv69** [comment]
> yes

But would you rather press a macro individually to toggle off modules or just deactivate the main module and then have it automatically deactivate all the other modules that are used with it?

**Comment by FluorideHistorian** [comment]
have the macro be the same key that the other module is on

**Comment by Absurv69** [comment]
> have the macro be the same key that the other module is on

But then everytime you toggle the module on the macro will turn it off?

**Comment by FluorideHistorian** [comment]
is that not what you want?
you enable autocrystal which turns off flight

**Comment by Absurv69** [comment]
> is that not what you want? you enable autocrystal which turns off flight

My bad i misunderstood what you said. Yes that is what i want, i think this feature is sorted then. Thanks for your input wouldn't have known without you.

**Comment by FluorideHistorian** [comment]
my pleasure
