### ISSUE TITLE
Crystal Aura/Kill Aura Friend Override Setting [FEATURE]

### ISSUE THREAD

**Issue by Absurv69** [RusherDevelopment/rusherhack-issues#1438]
This feature would give the client a new dropdown setting in both the kill aura module and the crystal aura module to override friends and ca/ka anyways + an optional threshold amount of damage received from a friend untill the override kicks in. The setting when toggled allows the ca/ka to ignore friends when they take damage from them, e.g. you have someone friended and the start to crystal you, the setting will kick in and your aura will target them. I'm not a coding wizz so im unsure whether you can make the client recognize which entity is damaging you. With the other max damage setting i mentioned to accompany this your friends can hit you and damage you a little bit (when messing around) but as soon as they start to damage you hard you will be able to protect yourself. This setting would be especially useful when you are friending someone that you do not know/do not trust fully.

Im not sure if this will function for crystal aura however, maybe the setting could be for kill aura only with a new setting under ka which overrides friends for crystal aura when you are dealt a certain amount of damage from a friend using kill aura? im pretty sure that would work

In an anarchy environment were not many people can be trusted this setting would really shine!

**Comment by FluorideHistorian** [comment]
for killaura this would be easy to make but it wouldnt work so well for autocrystal if its even possible

**Comment by Absurv69** [comment]
> for killaura this would be easy to make but it wouldnt work so well for autocrystal if its even possible

Yes i agree ca would be substantially harder to implement this into, however all they need to do is make it ignore friends when receiving a certain amount of damage from them.

**Comment by Absurv69** [comment]
> when you take damage from a crystal it doesnt tell you who placed it so it could work only if there so nobody else near i guess

Ahh that really sucks, i do think it would be a useful addition to ka atleast

**Comment by Absurv69** [comment]
> when you take damage from a crystal it doesnt tell you who placed it so it could work only if there was nobody else near i guess

Could it not somehow listen for a player hand swing and detect who its from

**Comment by FluorideHistorian** [comment]
a swing is just a simple animation packet
theres no other data

**Comment by Absurv69** [comment]
> a swing is just a simple animation packet theres no other data

Maybe the setting could be for kill aura only however it a new setting under ka which overrides friends for crystal aura when you are dealt a certain amount of damage from a friend using kill aura? im pretty sure that would work

**Comment by FluorideHistorian** [comment]
maybe it would just be best then to have an option to unfriend someone once they damage you a certain amount

**Comment by Absurv69** [comment]
> maybe it would just be best then to have an option to unfriend someone once they damage you a certain amount

I think both of our options would work, however auto unadding a friend would be annoying if they are actually your friend and you are just 1v1ing, this is a wide topic lmao you could even add a crystal aura target friends option!

**Comment by John200410** [comment]
I don't think this would be worth implementing. It doesn't really take long to unfriend someone manually
