### ISSUE TITLE
[BUG] Any changes to ElytraFly TargetY and EmergeAt dont stick

### ISSUE THREAD

**Issue by Andboniels** [RusherDevelopment/rusherhack-issues#1441]
**Describe the bug**
Any changes done to ElytraFly TargetY and EmergeAt dont change anything, it still flies at the default TargetY 200 and EmrgeAt 140

**To Reproduce**
Change settings and try and elytrafly with it on, you always fly with default.

**Other mods**
List other forge mods you are using (if any):
No other mods

**Expected behavior**
Flying within the TargetY
![RH Bug](https://user-images.githubusercontent.com/112793197/230703456-27996d84-ea2e-43a5-baa2-b45fb9fcdb43.jpg)

**Screenshots**

**Additional context**

**Comment by FluorideHistorian** [comment]
can anyone else confirm

**Comment by John200410** [comment]
they work fine
