### ISSUE TITLE
[FEATURE] AutoObsidian

### ISSUE THREAD

**Issue by Zamplex** [RusherDevelopment/rusherhack-issues#1443]
**What feature would you like to be added.**
AutoObsidian. Automatically mine echests for obsidian, would be a faser way of obtaining obsidian than mining manually.

**Is your feature request related to a problem? Please describe.**
None

**Additional context**
None

**Comment by FluorideHistorian** [comment]
nuker + scaffold

**Comment by FluorideHistorian** [comment]
also duplicate of a few issues
