### ISSUE TITLE
[FEATURE] Alt Botting

### ISSUE THREAD

**Issue by NovusRomulus** [RusherDevelopment/rusherhack-issues#1444]
**What feature would you like to be added.**
Minecraft alt account bots. (Similar to [OQMinebot](https://www.minecraftbot.com/)).
Have an integrated alt botting tool that uses Mineflayer or some similar system and lets us control alt accounts as bots and have some premade tasks (i.e., baritone + elytra fly, go to certain coordinates and drop loot, mine a large area, mine ores, bodyguards, raid alerts, farm afk, etc...) all within RusherHack. Have premade commands but let us make our own too.

**Is your feature request related to a problem? Please describe.**
Not a problem, just a suggestion :)

**Additional context**
Some of the available plugins for OQMinebot, similar ones could be available with RusherHack:
![image](https://user-images.githubusercontent.com/130174456/231332998-b39e1ae8-8d8a-4b9b-9465-2fca98327b45.png)

**Comment by John200410** [comment]
This would require a large amount of development effort and time for something not many people would use
