### ISSUE TITLE
[FEATURE] Player whisper addon (In spammer)

### ISSUE THREAD

**Issue by ICopedTooHard** [RusherDevelopment/rusherhack-issues#1445]
**What feature would you like to be added.** I'd like to "add" this feature inside this module which would be spammer and I'd like it so you can allow it to whisper 1 person instead of all so you'd pick a person and type the name and it'd only whisper to that person

A detailed explanation of what this feature should be. So inside the module Spammer as said before you'd be able to type that players name in and spam them with the TXT you've made and they'd get mad

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I want to personally spam one player but It's not an option on rusherhack so I'm left with no reason for RNG spamming

**Additional context**

**Comment by John200410** [comment]
You can add the whisper command to the spammer file itself with the player's name.
