### ISSUE TITLE
[BUG] I cant open Rusherhack

### ISSUE THREAD

**Issue by Hakki808** [RusherDevelopment/rusherhack-issues#1450]
Rusherhack wont open.

When launching RusherHack in Forge, a message pops up:
"Error 1077: could not connect to authentication servers. please try again later!"

To reproduce the bug i simply got to:
1. Open Minecraft
2. Chose Rusherhack 
3. Launch.

**Other mods**
I am not using any other mods.

**Expected behavior**
I expected to launch the game and play minecraft.

**Additional context**
I Updated the Minecraft Launcher, i Dont really know if it has anything to do with that.

**Comment by Aspect-404** [comment]
He pushed a patch: [@everyone if you are getting an "Error 1077" when trying to launch rusherhack, reinstalling rusherhack should fix the issue.](https://ptb.discord.com/channels/590970327870341143/813743945518415872/1098500367513309195)

**Comment by John200410** [comment]
Reinstalling will fix the issue
