### ISSUE TITLE
[FEATURE] Better hud

### ISSUE THREAD

**Issue by Zamplex** [RusherDevelopment/rusherhack-issues#1451]
**What feature would you like to be added**
Being able to change every hud elements scale individually and being able to choose if a module should be visible on the ArrayList in the settings for that module. 

**Is your feature request related to a problem? Please describe.**
It's not a problem, but customization of the hud would be easier and quicker

**Additional context**
None

**Comment by John200410** [comment]
You can already use the *drawn command to remove modules from the FeatureList.

There is already an issue open for hud element scaling #1369
