### ISSUE TITLE
[FEATURE] Safewalk and ForcePlace "On Hold" setting

### ISSUE THREAD

**Issue by Aspect-404** [RusherDevelopment/rusherhack-issues#1452]
**What feature would you like to be added.**
A setting under both Safewalk and ForcePlace, which will use the bind, but only activate on hold, similar to ExtraTab Toggle Setting, but vice versa. In that way, players may unbind crouching, and set Safewalk and ForcePlace to their former crouch bind, which allows them to have all of the positives of crouch but without the slowness it gives and without needing a NoSlow bypass for crouching speed. Already being toggleable though, it can be used in this way, however it takes quite some time to get accustomed to needing to toggle every time instead of holding.

**Is your feature request related to a problem? Please describe.**
Unrelated to an issue with the client.

**Additional context**
None

**Comment by John200410** [comment]
Hello,

You can bind a module as a hold bind by holding the key while binding the module.
