### ISSUE TITLE
[FEATURE] module visible setting

### ISSUE THREAD

**Issue by kdh8219** [RusherDevelopment/rusherhack-issues#1455]
**What feature would you like to be added.**
Module visible settings for module list that can be set for each module.
This hack is so confusing when many modules are turned on.
like lambda's this setting.
![](https://cdn.discordapp.com/attachments/580706821174591488/1104599032938115203/image.png)

**Comment by John200410** [comment]
You can use the *drawn command to his modules from the featurelist
