### ISSUE TITLE
[BUG] anchor

### ISSUE THREAD

**Issue by Microndo** [RusherDevelopment/rusherhack-issues#1457]
**Describe the bug**
Module Anchor: anchor will try to move you into a hole even if there is a block above it
**To Reproduce**
look at the screenshot

**Other mods**
future lambda

**Expected behavior**
me not to be stuck like it just freezes u instead of letting u walk normally 

**Screenshots**

**Additional context**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/123648323/8fcfe64b-e77e-4e59-a740-5e29a1dfcc2a)

**Comment by FluorideHistorian** [comment]
this has been fixed in v2.0
