### ISSUE TITLE
[BUG] Quiver

### ISSUE THREAD

**Issue by Microndo** [RusherDevelopment/rusherhack-issues#1458]
**Describe the bug**
Module Quiver: when you right click to shoot the arrow it shoots it and because this module is terrible it usually just hits the block above your head even when u have a 1 block space but sometimes it will work and hit you its pretty random. the bug is that once an arrow is shot and misses your head and goes into the roof rusher will sometimes think like you got shot with the arrow and won't let you shoot another until you pick that up

**To Reproduce**
shoot an arrow with a block of space above you and it will only happen sometimes

**Other mods**
future lambda

**Expected behavior**
it should try to hit me with another arrow instead of thinking the one which hit the ceiling hit me

**Screenshots**

**Additional context**

**Comment by FluorideHistorian** [comment]
> hits the block above your head even when u have a 1 block space
this is unfixable as shooting 1 tick earlier makes the arrow pass through you most the time

> won't let you shoot another until you pick that up
fixed in the next update
