### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Kepterv** [RusherDevelopment/rusherhack-issues#1461]
**Describe the bug**
Basically, when turning on extrachest and using fill the client tries to put shulker inside of a shulker as well and it straight up just stops (even if shulker boxes are in blacklist)

**To Reproduce**
Turn on extrachest and fill or use buttons and press fill while having inv full of stuff and shulkers

**Other mods**
earthhack, lambda

**Expected behavior**
Skip shulker boxes or at least have a working blacklist

**Comment by FluorideHistorian** [comment]
seems to be fixed in v2.0, reopen if not
