### ISSUE TITLE
Addition of Version Switching Functionality to Utility Mod

### ISSUE THREAD

**Issue by aledlb8** [RusherDevelopment/rusherhack-issues#1464]
**Feature Request**
I would like to propose the addition of a new feature to the utility mod, which involves incorporating version switching capabilities within the game. I came across a GitHub page (https://github.com/FlorianMichael/ViaMCP) that offers the ability to switch between versions within the game, and it provides an MCP package to be integrated into one's own utility mod.

**Problem Description:**
While this feature might not be a concern for everyone, it addresses a specific issue that I encounter. I often play on servers that are not on version 1.12.2. Currently, RusherHack is the only utility mod that effectively caters to my needs in such scenarios. Therefore, having version switching functionality within the utility mod would greatly enhance my gameplay experience on different servers with varying versions.

**Comment by FluorideHistorian** [comment]
rusherhack does not use mcp
you can use viaforge with rusherhack
https://www.curseforge.com/minecraft/mc-mods/viaforge

**Comment by aledlb8** [comment]
Oh, is that so? I didn't know that, well thanks for the clarification.
