### ISSUE TITLE
[FEATURE] Surround anticity

### ISSUE THREAD

**Issue by RandomUserEdkl3v** [RusherDevelopment/rusherhack-issues#1465]
**What feature would you like to be added.**
A module called "Blocker". Places blocks around surround block that is getting mined to prevent crystals being placed there.

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**
No.

**Comment by FluorideHistorian** [comment]
i dont think this is even useful anymore since you can place in 1x1 holes now

**Comment by FluorideHistorian** [comment]
AutoSurround has been rewritten and this has been included as a mode in the AntiCity setting
