### ISSUE TITLE
[BUG] Login button does nothing on installer.jar im on mac

### ISSUE THREAD

**Issue by Wall234** [RusherDevelopment/rusherhack-issues#1466]
**Describe the bug**

**To Reproduce**

**Other mods**
List other forge mods you are using (if any):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by FluorideHistorian** [comment]
you need the x86 version of java

**Comment by FluorideHistorian** [comment]
also this is not to ask for support, there is a support email on the website

**Comment by Wall234** [comment]
For mac?

**Comment by FluorideHistorian** [comment]
yes

**Comment by Wall234** [comment]
https://github.com/RusherDevelopment/rusherhack-issues/assets/120263979/f2725f62-5d1c-46b6-858e-3a10c9601be7

**Comment by Wall234** [comment]
LOok i did that but still

**Comment by FluorideHistorian** [comment]
you have the wrong version of java, please contact the support email
