### ISSUE TITLE
[FEATURE] AirPlace

### ISSUE THREAD

**Issue by wce2005a** [RusherDevelopment/rusherhack-issues#1467]
**What feature would you like to be added.**
AirPlace, lets you place blocks in the air around you

**Is your feature request related to a problem? Please describe.**
no
**Additional context**
some other clients have it, just lets you place blocks in the air like you can with liquid interact, and has modifiable range

**Comment by FluorideHistorian** [comment]
will add if someone dms me the bypass 😏

**Comment by FluorideHistorian** [comment]
this has been added in the next update
