### ISSUE TITLE
[BUG] Error 1077: Could not connect to authentication server

### ISSUE THREAD

**Issue by Yedues** [RusherDevelopment/rusherhack-issues#1468]
**Describe the bug**

Whenever I try to launch Rusherhack client, I get a message that says "Error 1077: Could not connect to authentication servers." This message has been popping up for me for a while and I also get the same message if I try to open the RusherInstaller file

**To Reproduce**

I do not know how to reproduce the behavior

**Other mods**
List other forge mods you are using (if any):

None

**Expected behavior**

The message should not appear and Rusherhack should launch without issue

**Screenshots**

The first screenshot is what happens if I launch rusherhack. The second screenshot is if I try to open RusherInstaller
![rusherhack](https://github.com/RusherDevelopment/rusherhack-issues/assets/108971132/73cfb58b-e650-4244-8121-cf7a46a0a4f1)
![rusherhack2](https://github.com/RusherDevelopment/rusherhack-issues/assets/108971132/9c375150-661d-4e52-ba2b-39457377d2a1)

**Additional context**

My access to the download file page has expired, I'm not sure if this have anything to do with the issue
![rusherhack3](https://github.com/RusherDevelopment/rusherhack-issues/assets/108971132/4a165ec4-d90c-4fac-b712-47b62a19d7ad)
I did see some posts on here saying that reinstalling would fix the issue, but I am unable to do that as I don't have access to reinstall it

**Comment by John200410** [comment]
You can redownload the installer from https://rusherhack.org/users/

Please do not use the github issue tracker to request support

**Comment by Yedues** [comment]
> You can redownload the installer from https://rusherhack.org/users/
> 
> Please do not use the github issue tracker to request support

I don't remember my account info

**Comment by John200410** [comment]
> > You can redownload the installer from https://rusherhack.org/users/
> > Please do not use the github issue tracker to request support
> 
> I don't remember my account info and I was unable to access the discord for support

Contact the support email address on the website

**Comment by Yedues** [comment]
> > > You can redownload the installer from https://rusherhack.org/users/
> > > Please do not use the github issue tracker to request support
> > 
> > 
> > I don't remember my account info and I was unable to access the discord for support
> 
> Contact the support email address on the website

Thank you
