### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Crech** [RusherDevelopment/rusherhack-issues#1470]
PortalGodMode cancel all packets. Player cant open chests/break blocks.After turning off the module, nothing changes

**Comment by FluorideHistorian** [comment]
it is patched on a lot of servers and works as intended

**Comment by Crech** [comment]
> it is patched on a lot of servers and works as intended

after turning of module u cant loading chunks or use villagers or riding horses

**Comment by FluorideHistorian** [comment]
relog

**Comment by Crech** [comment]
This is solved only if u delete rh folder

**Comment by FluorideHistorian** [comment]
you probably had portalgodmode enabled in your config
