### ISSUE TITLE
[FEATURE] - Pre 1.19.4 chunk comparison mod

### ISSUE THREAD

**Issue by 3vZVVm6V9A3O877TUqQD** [RusherDevelopment/rusherhack-issues#1471]
**What feature would you like to be added.**
A chunk comparison module which analyses the bedrock patterns in the nether (other method would need to be used in overworld since there are new bedrock patterns) with any previous seeds 2b2t has used to be able to follow pre 1.19 chunk trails.

**Is your feature request related to a problem? Please describe.**
New chunks module doesn't work in latest versions anymore, a new method of locating new chunks will need to be used

**Additional context**
You may be able to pinpoint the exact era on which the chunk trail was made depending on which seed is detected within the chunk, you would have to research the seed changes in the nether and the versions on which this occurred to make this additional feature possible.

**Comment by FluorideHistorian** [comment]
this was added
