### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Crech** [RusherDevelopment/rusherhack-issues#1473]
Add NewChunks and blockESP. This will greatly help in detecting old chunks

**Comment by FluorideHistorian** [comment]
NewChunks is (maybe) impossible in 1.20

**Comment by FluorideHistorian** [comment]
not sure what you mean by blockESP, it has search already

**Comment by Crech** [comment]
> NewChunks is (maybe) impossible in 1.20

possible its looking for liquid

**Comment by Crech** [comment]
> not sure what you mean by blockESP, it has search already

no its blockESP, like in meteor client. U can use search for portals but if u add some blocks like cooper (help see new chunks, because cooper ore doesnt spawn in 1.12) it would be very uncomfortable

**Comment by FluorideHistorian** [comment]
search can already do this
