### ISSUE TITLE
[FEATURE] beehive info

### ISSUE THREAD

**Issue by jewmeat** [RusherDevelopment/rusherhack-issues#1474]
**What feature would you like to be added.**
I would like for a feature to be added where you can glance over at a beehive or nest, and be able to see the honey level. It would be useful in 1.15+ when farming bees, at the moment I have to switch to the f3 menu to see this. It would be a nice feature to have on my hud while I am farming.

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by Reava** [comment]
The mod Jade adds the feature of info on blocks you highlight, but doesnt support bee nests as this require server info, but the mod MoreBeeInfo adds some.

https://modrinth.com/mod/morebeeinfo/
https://modrinth.com/mod/jade

**Comment by John200410** [comment]
This was added in v2.0:
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/43681932/79a07db1-a56f-4f81-9d90-5a38b3bb3a8b)
