### ISSUE TITLE
[BUG]  Disfunctional Waypoints

### ISSUE THREAD

**Issue by ElijahBare** [RusherDevelopment/rusherhack-issues#1475]
**Describe the bug**
waypoints do not word, seemingly anywhere out of renderdistance

**To Reproduce**
make a waypoint more than 200 blocks away on a server

**Other mods**
Baritone
FabricAPI
Sodium
Meteor
Custom

**Expected behavior**
should instead make a waypoint where you input.

**Screenshots**

**Additional context**

**Comment by John200410** [comment]
This should be fixed in the next update.
