### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Zamplex** [RusherDevelopment/rusherhack-issues#1476]
**Describe the bug**
Baritone is buggy, misses parkours in the nether, and shakes while doing any task. And just weird. 

**To Reproduce**
get baritone to do anything, #goto (cords) on a flat surface is the best way, or make it parkour but it is not as often. 

**Other mods**
List other forge mods you are using (if any):
Future
RH
Sodium 
Journeymap

**Expected behavior**
When doing a task, it behaves weirdly. 

**Screenshots**

**Additional context**

**Comment by Reava** [comment]
For the shaking, reduce randomLooking to lower values, but not 0, as this would break Baritone's ability to sprint in certain cases.

#setting randomLooking113 0.2
#setting randomLooking 0.01

As of parkour, it is not too reliable, so don't expect it to be a parkour pro. Baritone excels at classic movement, things that rely on diagonal jumps and other "complicated" things are much more likely to fail.

**Comment by John200410** [comment]
This should be fixed in the next update.
