### ISSUE TITLE
[BUG] ExtraTab not showing all players

### ISSUE THREAD

**Issue by kgtomi** [RusherDevelopment/rusherhack-issues#1480]
ExtraTab is not working properly, I can't see more players on the tablist, only the ammount of players that I can already see without turning on ExtraTab. I can change the MaxHeight of the tablist though, but it won't show any more players.
This works in another utility client, I tested it.

**To Reproduce**
Turn on the ExtraTab feature. The amount of players set doesn't matter.

**Other mods**
I currently have Sodium, ViaFabric and Meteor client in my mods folder with Rusherhack. (+ Baritone api + Fabric api)

**Expected behavior**
ExtraTab should be showing more players on the tablist when I increase it on the 'players' slider.

**Screenshots**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/143607947/fd28d64f-cc0f-4fa2-ad07-237a3f437120)
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/143607947/3f5ddb88-90e4-40b6-a532-c403ce84f860)
This is clearly not the full amount of players on the server.

![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/143607947/962c1baf-85c1-4d5a-9d5a-03a3747317ac)
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/143607947/dafa92fd-7c52-4389-bdad-51d78f7d86fb)
But when I turn off 'ExtraTab' and turn on 'BetterTab' in Meteor Client, it works. So I think it's an anti-cheat problem.

**Comment by FluorideHistorian** [comment]
this sounds like a mixin conflict, try without meteor

**Comment by John200410** [comment]
This is a mixin compatibility issue, you have to use one or the other for this feature due to the race condition.
