### ISSUE TITLE
[FEATURE] elytra sounds setting in elytra fly

### ISSUE THREAD

**Issue by GentlemanMC** [RusherDevelopment/rusherhack-issues#1481]
**What feature would you like to be added.**
a setting to turn on/off the elytraflying sounds (they are so loud)
**Is your feature request related to a problem? Please describe.**
i hate the sound *WOOOOOOSHHHHHHHHHHHHHHHHHHHHHHHHHHHH*

**Comment by Toska2b2t** [comment]
You can also edit the sounds in your minecraft settings for now

**Comment by FluorideHistorian** [comment]
duplicate of #1079
