### ISSUE TITLE
2b2t strafe mode for the grim update

### ISSUE THREAD

**Issue by FeydH** [RusherDevelopment/rusherhack-issues#1484]
**What feature would you like to be added.**
A Grim strafe mode for 2b2t

**Is your feature request related to a problem? Please describe.**
A new anti-cheat called grim which is movement-based, it would be nice to have the client updated to those changes, or at least modes for people who do not play 2b2t.

**Additional context**
No

**Comment by FluorideHistorian** [comment]
this is very unlikely to be added due to the way grims movement check works

**Comment by Badinek** [comment]
No it doesnt. Bozes “strafe” bypass is just vanilla autojump that rotates you depending on keys pressed.

**Comment by FluorideHistorian** [comment]
the sprint module has now has autojump
