### ISSUE TITLE
[BUG] Inventory cleaner blacklist resets if you leave and join back

### ISSUE THREAD

**Issue by Chiwarn** [RusherDevelopment/rusherhack-issues#1485]
The inventorycleaner module's blacklist 

turn on the inventory cleaner module then do *inventorycleaner blacklist add minecraft: (block name) and then close minecraft then re-open.
 
baritone, future client, fabric api, journeymap. litematica, malilib,
replaymod, rusherhack

I expected not to have the inventorycleaner blacklist reset

**Comment by John200410** [comment]
Fixed in the next update
