### ISSUE TITLE
[FEATURE] BedrockMiner

### ISSUE THREAD

**Issue by CherkaSSH** [RusherDevelopment/rusherhack-issues#1490]
**What feature would you like to be added.**
Will have several types of bedrock mining([with tnt](https://www.youtube.com/watch?v=4HTYh2Cr5uU), [without](https://www.youtube.com/watch?v=b8Y86yxjr_Y))

**Is your feature request related to a problem? Please describe.**
I was always frustraited with mining bedrock even with mods that suppose to help bec thay acn't rotate to "bypass" anticheat

**Comment by FluorideHistorian** [comment]
are there any methods that work on 2b2t?

**Comment by ImKindaSus** [comment]
Idk I don't play on 2b

**Comment by ImKindaSus** [comment]
But portals should work

**Comment by FluorideHistorian** [comment]
this would fit better in a plugin
