### ISSUE TITLE
Soul Fire is not seen as Fire by Rusherhack so Avoid does not work on it [BUG] [1.20.1] 

### ISSUE THREAD

**Issue by Jossamations** [RusherDevelopment/rusherhack-issues#1492]
**Describe the bug**
In the experimental 1.20.1 version of RH, Soul Fire is not counted as Fire and Avoid will not prevent you from walking into it.

**To Reproduce**
Enable the Avoid module (make sure 'fire' is enabled under it) and walk into Soul Fire.

[**GIF**](https://cdn.discordapp.com/attachments/1062504119014789250/1150200452563079178/ezgif-3-74cee4650c.gif)

**Comment by John200410** [comment]
Thank you for reporting this, it is now fixed in the next update.
