### ISSUE TITLE
[FEATURE] EntityList  item section

### ISSUE THREAD

**Issue by kertd** [RusherDevelopment/rusherhack-issues#1494]
It would be nice if possible to make it like Lambda where the items are also individual display, like gold apples x10.

Thank you

**Comment by FluorideHistorian** [comment]
like all items in render distance are one item?

**Comment by kertd** [comment]
> like all items of a type in render distance are one element?

Yes, insted of "Ítem x 100 " like it is now,  could be like  " Golden apples x 78 , Nether bricks x 22
