### ISSUE TITLE
[FEATURE] Self pop counter

### ISSUE THREAD

**Issue by XxHausemasterxX** [RusherDevelopment/rusherhack-issues#1495]
**What feature would you like to be added.**
Self pop counter

**Is your feature request related to a problem? Please describe.**
Notification when I pop

**Comment by FluorideHistorian** [comment]
this is technically possible with the notifications module but desktop notifications are annoying
i can probably add a setting to disable those

**Comment by FluorideHistorian** [comment]
this has been added to pvpinfo in v2.0
