### ISSUE TITLE
[BUG] Self-block doesn't work on strict 2bpvp

### ISSUE THREAD

**Issue by XxHausemasterxX** [RusherDevelopment/rusherhack-issues#1496]
**Describe the bug**
Self-block doesn't work on strict 2bpvp. I will be moved up if I enable self-block.

**To Reproduce**
Enable self-block on strict 2bpvp.

**Other mods**
List other forge mods you are using (if any):
- appleskin-fabric-mc1.20-2.5.0.jar
- baritone-api.jar
- fabric-api-0.88.1+1.20.1.jar
- future-1.20.1-earlyaccess.jar
- rusherhack-loader.jar
- sodium-extra-0.5.1+mc1.20.1-build.112.jar
- sodium-fabric-mc1.20.1-0.5.1.jar
- viafabric-0.4.10+40-main.jar

**Expected behavior**
Enable self-block and I will be inside the obsidian.

**Comment by FluorideHistorian** [comment]
its patched
