### ISSUE TITLE
[FEATURE/BUG] AutoTotem and AutoEat suggestions/fixes involving NoSlow 2b2t

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#1497]
This issue is about the NoSlow bypass which makes eating without slowdown work only in offhand.

**What feature would you like to be added.**
1. WalkingOnly setting in AutoTotem>AlternateWhen. Needed so it doesnt switch to your food when you right click while flying or riding mounts, since it is unnecessary.
2. AutoTotem keyheld set to right click causes a small rubberband if you are holding food in mainhand and attempt to eat. 
3. AutoTotem keyheld set to right click doesnt switch to offhand if youre looking at blocks with food in mainhand, instead it prioritizes eating with mainhand. This issue should also be related to SwordUse where the same thing happens.
4. ToolUse should be added instead of SwordUse.
5. AutoEat offhand switch setting should be added and take effect only when walking.

**Comment by FluorideHistorian** [comment]
no longer needed
