### ISSUE TITLE
[BUG] Jesus not applied to Waterlogged Seaweed

### ISSUE THREAD

**Issue by chungaloid** [RusherDevelopment/rusherhack-issues#1502]
**Describe the bug**
Jesus effect is not applied to water blocks with seaweed.

**To Reproduce**
1. Enable jesus feature
2. Walk onto water block containing seaweed

**Expected behavior**
Water should have solid bounding box but isnt on the seaweed. Solid bb is applied only to the empty water blocks.

**Additional context**
May be worth checking if this happens to the kelp water as well. It seems like most waterlogged blocks are affected but its only really an issue with the seaweed and kelp, or any other waterloggable blocks that are not solid.

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
