### ISSUE TITLE
ExtraChest Search Steal/Fill compatibility [FEATURE]

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#1504]
**What feature would you like to be added.**
After searching for an item using the ExtraChest search bar, steal/fill buttons would take only these items. Should be toggleable under the Search option.

**Is your feature request related to a problem? Please describe.**
Adding and deleting the items with a command is way too much of a bother. 

**Additional context**
This feature was suggested by my friend. It sounds pretty useful so it would be a nice addition to the Search function.

**Comment by John200410** [comment]
This has been added in the next update: 

https://github.com/RusherDevelopment/rusherhack-issues/assets/43681932/b69bba8b-a591-4b8f-855d-a203efb59792
