### ISSUE TITLE
Minecraft instance addons [FEATURE]

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#1506]
**What feature would you like to be added.**
Instead of having a minecraft instance named "Minecraft (version)" with a block icon, this module would replace your instance name with the account youre currently logged in with. Ideally, the icon would be replaced with the head of your accounts skin.

**Is your feature request related to a problem? Please describe.**
When having multiple instances open while multitasking and switching between them often, it can be hard to keep track of which instance has which account. This feature would make this easier.

**Additional context**
me when the

**Comment by John200410** [comment]
I have created a plugin for this: https://github.com/John200410/rusherhack-instance-info
