### ISSUE TITLE
ExtraTooltips for written books [FEATURE]

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#1507]
**What feature would you like to be added.**
Would display a preview of the first page of a book youre hovering over with the cursor.

**Is your feature request related to a problem? Please describe.**
Not really, it just seems like a nice thing to have.

**Additional context**
ez

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/43681932/18d81404-b2e4-48e8-a69b-754358e28858)
