### ISSUE TITLE
[BUG] Waypoints will not save my changes

### ISSUE THREAD

**Issue by SpicyCitrus** [RusherDevelopment/rusherhack-issues#1510]
**Describe the bug**
i made a waypoint and wanted to delete a few days later and when i do delete it. It goes away but then the next day its back.
please help

**To Reproduce**
create a waypoint>close game>open game and delete waypoint> relaunch

**Other mods**
List other forge mods you are using (if any): none

**Expected behavior**
i expect the waypoint to be deleted forever

**Screenshots**
i have no screenshots

**Additional context**
none

**Comment by FluorideHistorian** [comment]
try to run the command *config save before closing your game
