### ISSUE TITLE
[FEATURE] Elytrafly for baritone

### ISSUE THREAD

**Issue by CheqrkaSSH** [RusherDevelopment/rusherhack-issues#1514]
So you know there is a baritone elytrafly rn, so can you make a basic elytra for it that would have a speed of a normal firework rocket

My problem is that i play on servers that allow this wype of elytrafly but i want to use baritone elytrafly too

Plz make for legacy and 1.20 versions

**Comment by ImKindaSus** [comment]
I know i described it pretty badly

**Comment by John200410** [comment]
why don't you just use baritone's elytra pathfinding?

Also legacy rusherhack is no longer going to receive any feature updates

**Comment by ImKindaSus** [comment]
> why don't you just use baritone's elytra pathfinding?
> 
> Also legacy rusherhack is no longer going to receive any feature updates
The thing is that it uses fireworks to fly, but i need it to fly without them

**Comment by Badinek** [comment]
1.12 version will only be getting bug fixes (if that) from now on.

**Comment by FluorideHistorian** [comment]
this seems more like a baritone feature request, open an issue on their git page
