### ISSUE TITLE
AutoDisconnect TotemCheck improvements [FEATURE]

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#1517]
**What feature would you like to be added.**
TotemCheck should have 2 subsettings added: Amount and OnPop. 
Amount- AutoDisconnect will disconnect you only after you reach set totem threshold in your inventory. 
OnPop- AutoDisconnect will disconnect you when you pop a totem. Amount setting would get hidden upon enabling it since it would be useless. 

**Is your feature request related to a problem? Please describe.**
Current TotemCheck is quite lacking, since if its disabled you get disconnected even though you are carrying 10 totems or more. This is very inefficient travelling wise. If the setting is on, it will only disconnect you after you run through all your totems, and you are prone to dying easily upon reconnect. 

**Additional context**
This is already known but AutoDisconnect should also stop accounting for absorption hearts when it comes to the Health setting.

**Comment by FluorideHistorian** [comment]
autodisconnect already ignores absorption

**Comment by FluorideHistorian** [comment]
both settings have been added
