### ISSUE TITLE
[BUG] Position HUD Element

### ISSUE THREAD

**Issue by Skai256** [RusherDevelopment/rusherhack-issues#1518]
**Describe the bug**
the position hud element with interdimensional set to separated does not display overworld coordinates while in the nether, all other interdimensional modes (except for off obviously) display overworld coordinates. separated mode also doesnt have the interdimensional y option

**To Reproduce**
enable position hud element
set interdimensional to separated
enter the nether
no overworld coordinates

**Other mods**
sodium, a few others that should not affect this
(testing was done on a separate instance as well with only fabric api and rusherhack, still happens)

**Expected behavior**
enable position hud element
set interdimensional to separated
enter the nether
overworld coordinates should be in brackets beside the nether x and z with optional y value setting

**Screenshots**
![config](https://github.com/RusherDevelopment/rusherhack-issues/assets/132626948/e284a767-8ba5-40fd-a545-c5959796d22e)

**Additional context**
scarlet is a cute cat

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
