### ISSUE TITLE
[FEATURE] Add OreSim/SeedMapper

### ISSUE THREAD

**Issue by Glebux** [RusherDevelopment/rusherhack-issues#1522]
**What feature would you like to be added.**
OreSim is an xray based on the world seed implemented in meteor-rejects repo, and seedmapper can locate structures, biomes, loot and more using the world seed.

**Is your feature request related to a problem? Please describe.**
Really annoying when server owners use anti-xray on their servers. 

**Additional context**
Nothing.

**Comment by John200410** [comment]
What server are you using rusherhack on? Please keep in mind that rusherhack is made to be used on anarchy servers only. If you really want this feature you can create a plugin in rusherhack for it
