### ISSUE TITLE
[FEATURE] Mouse Hover Item Mover

### ISSUE THREAD

**Issue by SagoTooBeeTooTee** [RusherDevelopment/rusherhack-issues#1524]
**What feature would you like to be added.**
A module that lets you drag items quickly by holding shift and hovering your mouse over the items. I've attached an example video.

https://github.com/RusherDevelopment/rusherhack-issues/assets/148032609/3e471aad-4daa-4371-9a2d-d9adf1d0cf31

**Comment by John200410** [comment]
There exists a plugin that can do this: https://github.com/rfresh2/ContainerTweaks-rusherhack
