### ISSUE TITLE
Slowswing for 1.20.1 Rusherhack in Animations

### ISSUE THREAD

**Issue by NewHag** [RusherDevelopment/rusherhack-issues#1527]
Slowed swinging animation
Just slows down how fast you swing. And make it work when swinging fast, like when using AutoCrystal. And add an option or slider to change the speed of the animation.

**Comment by GurteX** [comment]
@FluorideHistorian cn u remove his breathing ability for me please?

**Comment by FluorideHistorian** [comment]
there is a speed setting in the swing module now
