### ISSUE TITLE
Cap PlayerView rotation

### ISSUE THREAD

**Issue by hashalite** [RusherDevelopment/rusherhack-issues#1535]
**Is your feature request related to a problem? Please describe.**
It seems like the player view element “accumulates” rotation over time. For example, if you do three full rotations to the left, the model will be stuck facing left until you do three full turns to the right.
Maybe you could cap whatever is keeping track of the model's rotation?

**Additional context**
https://cdn.discordapp.com/attachments/1181333656715919503/1181333732548939776/2023-12-04_15-27-54.mp4

**Comment by John200410** [comment]
This has been fixed in the next update
