### ISSUE TITLE
[BUG] Dupicate category in GUI

### ISSUE THREAD

**Issue by goldendrip** [RusherDevelopment/rusherhack-issues#1538]
**Describe the bug**
The option 'classic' creates a duplicate when pressed.

**Other mods**
List other forge mods you are using (if any):
Future client 
Sodium

![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/81508141/6222c7b5-557c-43b6-a12d-e47f01eb9520)

**Comment by John200410** [comment]
This has been fixed in the next update
