### ISSUE TITLE
[FEATURE] Hide waypoints individually

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#154]
**What feature would you like to be added.**

Ability to turn off specific waypoints. Would help to have a "public" indicator while streaming but keep private stuff hidden. Could be managed via waypoints window (see #86)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update: https://rusherhack.org/i/m8kaldxpiv.mp4
