### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by asdAet** [RusherDevelopment/rusherhack-issues#1541]
Is your feature request related to a problem? Please describe.**
There is a problem in entitylist when there are many identical items, they are written in 64 and not in the total number, as when there are too many items they go beyond the border of the screen, it is very inconvenient.

![javaw_xctmiVCMgf](https://github.com/RusherDevelopment/rusherhack-issues/assets/101425999/b9d16568-9080-4378-868a-5b68af8a799f)

it would be more convenient like this

![ApplicationFrameHost_iKjSW1SA4S](https://github.com/RusherDevelopment/rusherhack-issues/assets/101425999/f1c6f080-019d-4915-ae06-b0e94ac18c74)

**Comment by Taylhurx** [comment]
this would be nice to have instead of it on;y counting stacks and then going to another

**Comment by FluorideHistorian** [comment]
i have fixed this in the next update
