### ISSUE TITLE
[BUG] Extrachat friend mentions disabled but still ping

### ISSUE THREAD

**Issue by NinetyUnderScore** [RusherDevelopment/rusherhack-issues#1543]
### Describe the bug
When the ExtraChat module is enabled, with sound on and Mentions->Friends disabled, the ping sound is still played every time a friend's username is sent or even when a friend sends a message.

### To Reproduce
1. Enable ExtraChat
2. Enable ExtraChat->Mentions
3. Disable ExtraChat->Mentions->Friends, 
4. Enable ExtraChat->Sound
5. Have another player send the name of someone on your friends list in chat, or alternatively, have the friended user send a message in chat.

### Other mods
*Fabric 1.20.1*
AppleSkin
Baritone
Carpet Mod
Continuity
EntityCulling
FabricAPI
Indium
Litematica
Lithium
MaLiLib
Mod Menu
Nvidium
Puzzle
RusherHack Fabric Loader
Sodium
Tweakeroo
UI Utils
Xaero's Minimap
Xaero's World Map

### Expected behavior
For no ping sound to be played when a friend sends a message or when a friends username is sent in chat.

### Screenshots
Config:
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/81204025/d4dc04ce-ee1a-4243-b853-578d0944121b)

### Additional context
N/A

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
