### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by LogicalArithmetic** [RusherDevelopment/rusherhack-issues#1544]
Water movement for control elytrafly.
This would be a setting within control elytra fly that can be toggled on and off and would allow the player to use control elytrafly while submerged in water.
You can't use control elytrafly in water without the setting.
Other clients such as meteor and future have this feature as a setting within the control elytrafly module.

**Comment by FluorideHistorian** [comment]
this has been added in the next update
