### ISSUE TITLE
[FEATURE] Ghost Hand

### ISSUE THREAD

**Issue by PappyVanPoodle** [RusherDevelopment/rusherhack-issues#1545]
**What feature would you like to be added.**
The ability to open chests, use furnaces, etc. through walls like you can through the use of FaceCam, except first person.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to open chests quickly through walls in places like dungeons, villages, bastions and being quickly swarmed by mobs that could have been prevented if I were able to open the chest through the wall.

**Comment by FluorideHistorian** [comment]
this was added recently
