### ISSUE TITLE
[FEATURE] ExtraTooltips Bee Counter/Honey Level

### ISSUE THREAD

**Issue by P529** [RusherDevelopment/rusherhack-issues#1546]
**What feature would you like to be added.**
An option in ExtraTooltip to display the amount of bees in a hive or a nest and the current level of honey accumulated.

**Is your feature request related to a problem? Please describe.**
The only problem there is, is that I can't see how many bees are in a hive or what the level of honey is unless I turn on NBT Data and have to comb through a lot of data q.q

**Additional context**
Its based and a quick thing to add :)

**Comment by John200410** [comment]
This has been added in the next update:
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/43681932/03f51d8a-a968-4577-9816-da893bed9ba2)
