### ISSUE TITLE
[FEATURE] mostly about no render improvements

### ISSUE THREAD

**Issue by vnikjr** [RusherDevelopment/rusherhack-issues#1549]
**What feature would you like to be added.**
feature idea 1: anchor aura (same a crystal aura but for respawn anchor pvp)
feature idea 2: more specific no render options (the ability to set the exact entities/blocks that you want to not get render'd)

**Is your feature request related to a problem? Please describe.**
the idea behind feature 2 is that sometimes when you make lag machines but dont wanna lag urself to death you would use a no render mod but when you make a lag machine with a concept never used b4 which is not included in the mod settings (for instance snowballs) so i think it would be really nice to have a complete list of entities/blocks to not render (could be done with a search window where you could search something like minecraft:enchant_table) and the mod would stop those from rendering

**Additional context**
none

**Comment by FluorideHistorian** [comment]
anchoraura was already suggested in #1511
norender entities is a plugin now
norender blocks was already suggested in #590
