### ISSUE TITLE
[BUG] glow makes double holes only render 1 hole

### ISSUE THREAD

**Issue by xyzbtw** [RusherDevelopment/rusherhack-issues#1550]
**Describe the bug**
When you turn on glow and have double holes enabled, it only renders for 1 of the double holes

**To Reproduce**
Turn on holeesp, doubles and glow

**Other mods**
List other forge mods you are using (if any):
future, phobot, and a few rendering mods such as sodium 

**Expected behavior**
For glow to render for both holes

**Comment by John200410** [comment]
Thank you for reporting this. This has been fixed in the next update.
