### ISSUE TITLE
The crosshair module [BUG] 

### ISSUE THREAD

**Issue by Taylhurx** [RusherDevelopment/rusherhack-issues#1555]
if you enable the crosshair there is no hit timer and it could mess up people timeing with hitting it would be nice if you could try to add it to the crosshair moudule and I think a lot of people would like it to be added as a thing

**Comment by FluorideHistorian** [comment]
just use killaura 😎

**Comment by FluorideHistorian** [comment]
this has been fixed but you still should just use killaura
