### ISSUE TITLE
[FEATURE] AutoCommand

### ISSUE THREAD

**Issue by roshanarunk** [RusherDevelopment/rusherhack-issues#1556]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

Repeat a command or macro after a set interval either indefinitely or a set amount of times.

**Is your feature request related to a problem? Please describe.**

Using baritone to AFK farm by repeating a macro every X minutes.

**Additional context**

**Comment by John200410** [comment]
You can use Spammer to do this. To make it only execute the command a set amount of times, you can make spammer toggle itself off via command
