### ISSUE TITLE
Armor hud [BUG] 

### ISSUE THREAD

**Issue by Taylhurx** [RusherDevelopment/rusherhack-issues#1557]
when I look at the armor hud menu in gms it is where it is suposed to be but when I go in gmc it bugs out and moves it's self here I will send 2 screenshots of when I am in gms and when I am in gmc
![2024-01-18_19 53 15](https://github.com/RusherDevelopment/rusherhack-issues/assets/121765937/11c63d57-9e7d-4795-aa13-f70f68afee56)
![2024-01-18_19 53 36](https://github.com/RusherDevelopment/rusherhack-issues/assets/121765937/d07622f9-ca31-45b6-9123-e32ff36a643b)

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
a temporary solution is to disable the waterraise setting

**Comment by Taylhurx** [comment]
rhanks

**Comment by FluorideHistorian** [comment]
my pleasure

**Comment by Taylhurx** [comment]
what does it do tho?

**Comment by FluorideHistorian** [comment]
what does what do

**Comment by Taylhurx** [comment]
the waterraise

**Comment by FluorideHistorian** [comment]
explained in the discord

**Comment by Taylhurx** [comment]
k
