### ISSUE TITLE
Client crashes after relog (wifi disconnect) [BUG] 

### ISSUE THREAD

**Issue by loupeznikvicko** [RusherDevelopment/rusherhack-issues#1563]
**Describe the bug**
Whenever my wifi shuts down i reconnect to the server and i try to use my elytra fly, whole MC crashes. (Autowalk, ely fly [control] and ely tweaks are used)

**To Reproduce**
Turn off wifi for about 20 seconds, let the server disconnect you, reconnect to server and turn all of the modules mentioned on again.

**Other mods**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/134846760/e35840d9-98e1-4ae4-837b-9a14488e06f7)

**Expected behavior**
A week ago i had not a single issue, even after disconnect i could use ely fly with no issues. I didnt do any changes to my mods.

**Screenshots**
^^^^

**Comment by John200410** [comment]
Please upload a crash log
