### ISSUE TITLE
[BUG] ElytraFligth HighwayObstacle (Baritone) 

### ISSUE THREAD

**Issue by bastianmarin** [RusherDevelopment/rusherhack-issues#1566]
**Describe the bug**
Although this is not totally a "bug", it is something very annoying that I have "fixed" with a macro
The problem is when you deactivate elytra flight and it is "passing obstacles" it will continue and does not stop baritone with the module

**To Reproduce**
- activate elytra flight
- configure it to pass obstacles on the highway
- stop it while it is passing obstacles

**Other mods**
List other forge mods you are using (if any): N/A

**Expected behavior**
Option that says Stop Baritone with Module, this way it will send the Baritone API the action to stop when stopping the module.

**Screenshots**
https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/c1892e7e-1be9-4f10-bea9-f69b8e567232

**Additional context**
The video shows the solution with the macro because now I see that it is impossible to unbind a macro without deleting it :), I will open another issue

**Comment by John200410** [comment]
This has been fixed in the next update.
