### ISSUE TITLE
[BUG/FEATURE] Macro unbind doesn't exists

### ISSUE THREAD

**Issue by bastianmarin** [RusherDevelopment/rusherhack-issues#1567]
**Describe the bug**
there is no way to unbind a macro without actually deleting it with -macro
"-" = command handler rh

**To Reproduce**
- use *macro

**Other mods**
List other forge mods you are using (if any): N/a

**Expected behavior**
add a command to unbind the key macro without deleting it

**Screenshots**
![imagen](https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/dcc568f4-d545-49a4-b0bb-dc09a31fe3da)

**Additional context**
I found it uploading other issues :(

**Comment by John200410** [comment]
You can bind it to NONE
