### ISSUE TITLE
[BUG] timer causing the game to act different then expected in singleplayer

### ISSUE THREAD

**Issue by vnikjr** [RusherDevelopment/rusherhack-issues#1569]
**Describe the bug**
when using the module "timer" to slow down time in single player it can cause certain things to act differently to how they would at normal tps

**To Reproduce**
step one place a piston with a slime block on top
enable timer at a speed setting of 0.4 or lower
power the piston while standing on the slime block
you should get pushed into the slime block

**Other mods**
List other forge mods you are using (if any):
meteor client (no features enabled)

**Expected behavior**
you get launched up as you would with vanilla tick speed

**Screenshots**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/45495711/2f2fcf3f-07cd-4db9-8294-06d63cb86b15)

**Additional context**
none

**Comment by FluorideHistorian** [comment]
shrimply dont use timer in singleplayer

due to the way timer works this is pretty much impossible to fix on our end
