### ISSUE TITLE
[FEATURE]Better Customizability 

### ISSUE THREAD

**Issue by Nuclearpotato69** [RusherDevelopment/rusherhack-issues#1570]
**What feature would you like to be added.**
Like for example like how meteor client has the esp where you can choose from every mob in the game 

**Is your feature request related to a problem? Please describe.**
when i am building a snowball lag machine and i can make the snow balls disappear but not the water particles

**Comment by Nuclearpotato69** [comment]
also maybe some more focus on utility stuff not for 2b2t

**Comment by John200410** [comment]
You can use the Search module to search for specific entities, via using the *search entities add command.

Can you please elaborate on what exactly you want added?

**Comment by Nuclearpotato69** [comment]
im not searching for entities tho i want to make specific ones not render
