### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by LineZer0z** [RusherDevelopment/rusherhack-issues#1576]
**What feature would you like to be added.**
add a search box to auto craft to find recipes faster

**Is your feature request related to a problem? Please describe.**
its just not fun to scroll through every recipe in a list that has really small text

**Comment by John200410** [comment]
When using the command to set the value you can search through the options by typing your search query:
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/43681932/9a2e9a62-12bf-44e5-85b0-463fe64a9483)
