### ISSUE TITLE
[BUG] Smooth Freelook animation is fps based

### ISSUE THREAD

**Issue by tumen102** [RusherDevelopment/rusherhack-issues#1584]
**Describe the bug**
The animation on free-look's smooth setting speed is based on the amount of FPS you are getting. this means if you have high frames, it is very quick, and low frames mean it is slow.

**To Reproduce**
Enable Smooth Freelook
Enable free look with high fps
Set max FPS to 10 and re-enable it, it should be slower

**Other mods**
List other forge mods you are using (if any):
n/a

**Expected behavior**
the animation plays at a consistent speed no matter the fps

**Screenshots**
n/a

**Additional context**
this isn't really important lmao

**Comment by Auxnos** [comment]
can be fixed with a lerp formula that accounts for frame timing

**Comment by John200410** [comment]
Fixed in the next update
