### ISSUE TITLE
[BUG] Background text doesn't get darkened when in search bar

### ISSUE THREAD

**Issue by TgZ39** [RusherDevelopment/rusherhack-issues#1591]
# Describe the bug
When you type something in the search bar for the modules and the options show up the text for the modules in the module tabs don't get darkened.

# To Reproduce
1. disable custom font
2. open the rusherhack GUI
3. type something in the search bar

# Other mods
no mods

# Screenshots
## With custom font:
![grafik](https://github.com/RusherDevelopment/rusherhack-issues/assets/71944761/93c4024a-6287-4de1-9f4b-1af73fd239c2)

---

## Without custom font:
![grafik](https://github.com/RusherDevelopment/rusherhack-issues/assets/71944761/04302dfa-42b1-4278-bc47-5de7e398f786)

# Additional context
## My System:
- Linux (Fedora 39)
- Minecraft version 1.20.4 with Fabric
- CPU: R5 5600X
- GPU: RX 6600XT

**Comment by John200410** [comment]
This is fixed in the next update
