### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ZanTQrow** [RusherDevelopment/rusherhack-issues#1592]
**Describe the bug**

i am physically incabable of downloading the rush client beyond the installer as when i open said installer it gives up entirely and opens a black window for half a second before immediately shutting down

**To Reproduce**
Steps to reproduce the behavior: i am unsure

**Other mods**
List other forge mods you are using (if any): none

**Expected behavior**
A clear and concise description of what you expected to happen. Installing The Client

**Screenshots**
If applicable, add screenshots to help explain your problem. all i could give is a screenshot of me trying to use java to install it

**Additional context**
 ive had problems for 4 days now trying to get this

**Comment by John200410** [comment]
Please contact support for support inquiries: rusherbot2b2t@gmail.com
This github repository is for tracking bugs and feature suggestions
