### ISSUE TITLE
Not picking up specific item

### ISSUE THREAD

**Issue by 1F1R11** [RusherDevelopment/rusherhack-issues#1598]
**What feature would you like to be added.**
Not picking up items. You can add or del items from list such as *search command. If you add items to this list you will not be able for picking up them.

**Is your feature request related to a problem? 
For example, sometimes you didn't want to pick up dirt or cobblestone but you have empty slot in your inventory.

**Comment by FluorideHistorian** [comment]
this is just the inventorycleaner module
