### ISSUE TITLE
Chest preview 

### ISSUE THREAD

**Issue by 1F1R11** [RusherDevelopment/rusherhack-issues#1599]
**What feature would you like to be added.**
When you can reach to chest you can see it's inventory but not open it. It's scaling by distance.

**Is your feature request related to a problem?**
Yes, it is. Sometimes you don't have enough time for opening the chest. This feature makes your experience of playing more comfortable.

**Comment by theblazehen** [comment]
I use the Chest Tracker and wthit mods to do this, for the time being

**Comment by John200410** [comment]
You can't see what items are in a chest without opening it

**Comment by audsis** [comment]
you could make something like that but for chests you have opened already
