### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PhilipPanda** [RusherDevelopment/rusherhack-issues#1600]
Found a small bug, if you get suffocated in sand, all the visuals start acting weird.

**Comment by John200410** [comment]
Can you please record a video showcasing the issue?

**Comment by PhilipPanda** [comment]
Sure, might be device specific however it's very strange.

**Comment by FluorideHistorian** [comment]
did you ever record a video showing this

**Comment by PhilipPanda** [comment]
no i didint and its a super old issue dont matter anymore
