### ISSUE TITLE
[FEATURE] Trident Boost

### ISSUE THREAD

**Issue by Glebux** [RusherDevelopment/rusherhack-issues#1604]
**What feature would you like to be added.**
This module manipulates how the Riptide enchant works, it has 2 options:
1. The speed slider will change the multiplier of speed of the Riptide throw (patched on 2b)
2. Out of water checkbox, this allows usage of the Riptide enchant outside of water, even when it's not raining (works on 2b)

**Is your feature request related to a problem? Please describe.**
Not really, the only thing that frustrates me that other utility clients have, meteor for example

**Additional context**
Meteor Client has this feature already implemented, so it would be much easier to implement it here too

**Comment by John200410** [comment]
TridentTweaks added in v2.0.3
