### ISSUE TITLE
[BUG] Auto disconnect y level not working

### ISSUE THREAD

**Issue by Amiaoghg** [RusherDevelopment/rusherhack-issues#1610]
**Describe the bug**
Auto disconnect does not work with y level occasionally

**To Reproduce**
Jump from a high level down, occasionally does not work

**Other mods**
Sodium, Future

**Expected behavior**
When my y level is below a certain value, it disconnects

**Screenshots**

**Additional context**
This only occasionally happens, and re-logging fixes the issue.

**Comment by Amiaoghg** [comment]
![Screenshot 2024-04-27 135440](https://github.com/RusherDevelopment/rusherhack-issues/assets/89285433/f0b06cb9-c406-44a9-a994-6cbc7d2f657a)

Tried with and without illegal disconnect

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
