### ISSUE TITLE
AutoCrystal not targetting pre-existing crystals [BUG] 

### ISSUE THREAD

**Issue by ValkLaz** [RusherDevelopment/rusherhack-issues#1611]
**Describe the bug**
Auto Crystal does not target already placed crystals when it's **target > priority** is set to **damage** or **damage ratio**.

**To Reproduce**
Steps to reproduce the behavior: Reset AutoCrystal config then turn the target priority to damage or damage ratio. Make sure a crystal is already placed near a fakeplayer or enemy.

**Other mods**
List other mods you are using (if any): Meteor Client, Sodium, Nvidium, Lithium, ViaFabricPlus

**Expected behavior**
It's supposed to explode the crystal that was placed before the module was on.

**Comment by Erlhyenaplays** [comment]
try turning off only own in ca options

**Comment by FluorideHistorian** [comment]
> try turning off only own in ca options

not a setting in rusherhack autocrystal

**Comment by Erlhyenaplays** [comment]
Oh, Ok! Thanks for letting me know. People are better off using BlackOut with Meteor Client, as RH CA is not the best.

**Comment by Erlhyenaplays** [comment]
or maybe 

> **Describe the bug** Auto Crystal does not target already placed crystals when it's **target > priority** is set to **damage** or **damage ratio**.
> 
> **To Reproduce** Steps to reproduce the behavior: Reset AutoCrystal config then turn the target priority to damage or damage ratio. Make sure a crystal is already placed near a fakeplayer or enemy.
> 
> **Other mods** List other mods you are using (if any): Meteor Client, Sodium, Nvidium, Lithium, ViaFabricPlus
> 
> **Expected behavior** It's supposed to explode the crystal that was placed before the module was on.

Try using ThunderHack or Meteor with BlackOut addon

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
