### ISSUE TITLE
[FEATURE] FastBreak Double Break

### ISSUE THREAD

**Issue by bastianmarin** [RusherDevelopment/rusherhack-issues#1612]
**What feature would you like to be added.**
In summary, it is using the double break mechanics that is possible by packet, in the queu, thus breaking the queu twice as fast.

**Is your feature request related to a problem? Please describe.**
See video

**Additional context**
Nothing

Uploading Base Profile 2024.04.29 - 19.36.48.03.mp4…

**Comment by bastianmarin** [comment]
https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/ecd4993b-897e-49c5-b0e6-403a3fb9d2d2

**Comment by FluorideHistorian** [comment]
coming soon:tm:

**Comment by FluorideHistorian** [comment]
added in the next update
