### ISSUE TITLE
[BUG] ElytraBounce "Crash"

### ISSUE THREAD

**Issue by bastianmarin** [RusherDevelopment/rusherhack-issues#1615]
**Describe the bug**
The error occurs when using the elytrabounce module in rh

**To Reproduce**
There is no exact way to reproduce it, which is why it is COMPLETELY difficult for me to report. It happens after spending several hours/minutes with Elytra Bounce, there is nothing to indicate that this will happen to you, it is more frequent if you have the game tabbed, but it does happen with the game maximized

**Other mods**
![imagen](https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/c4b20a77-f74f-4a7b-aa5b-c8cc21762863)

**Expected behavior**
let this not happen

**Screenshots**
https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/2215bbf3-c4d9-4419-89e8-a6fa1a4a59fe

**Additional context**
I suspect that this is happening because the "Main Threader" is being collapsed with some type of while or task that leaves it waiting for a response and it gets stuck.

**Comment by bastianmarin** [comment]
a friend told me that a rh mod on discord told him to try extrachat, but i'm really not sure at all if it has anything to do with this one or not.

**Comment by bastianmarin** [comment]
![imagen](https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/e673f7f4-84d1-4204-a0a8-c35e5b65f052)
Modules actives when these crashes occur

**Comment by bastianmarin** [comment]
![imagen](https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/fdb394ad-08ad-4b8f-a090-0096825d1d6c)
also when this happens I always appear looking at this position when I open the game again, maybe it could be something about overflow in the axis aling search or something like that

**Comment by ShayBox** [comment]
I'm also having this crash about every hour, the game starts to lag a few seconds before, which gives me enough time to stop elytra fly and leave the server before it crashes.

**Comment by ShayBox** [comment]
I noticed during the lag prior to the crash that all my ram (32GB) and swap (32GB) were being used by Minecraft, even though my limit is 8GB.

**Comment by John200410** [comment]
Is this reproducible when rusherhack is the only mod present?

**Comment by John200410** [comment]
Unable to reproduce
