### ISSUE TITLE
[FEATURE] Armor HUD module to use DrawContext#drawItemInSlot

### ISSUE THREAD

**Issue by ShayBox** [RusherDevelopment/rusherhack-issues#1616]
This might be a weird request, but I use my own mod Durability101, which is just a basic mixin to the vanilla DrawContext#drawItemInSlot method to draw text above the vanilla durability bar.

 I noticed the Armor HUD module doesn't use that vanilla method to render the overlay, could it be changed to use that or a toggle to switch it to the vanilla rendering method for compatibility?

https://github.com/ShayBox/Durability101/blob/master/Fabric-1.20/src/client/java/com/shaybox/durability101/mixin/client/DrawContextMixin.java

![Screenshot 2024-05-01_201325](https://github.com/RusherDevelopment/rusherhack-issues/assets/9505196/90095e66-ae6d-4bdd-923f-ac1fd7ad7854)

**Comment by John200410** [comment]
Not possible with the way rusherhack's ui rendering works.
You can use the Durability setting in the Armor hud element to see the item's durability
