### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Zamplex** [RusherDevelopment/rusherhack-issues#1618]
**Describe the bug**
The bosstack render module makes the bossbar look weird. It's black and purple. 

**To Reproduce**
I just use bosstack. 

**Other mods**
Futureclient
Baritone
Iris
sodium
ViaFabricPlus
Journeymap

Note: it still happens if I only use RH. 

**Screenshots**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/73429097/ca4a8b0b-6b84-4f3d-ba21-4aad5d2903f3)

**Comment by FluorideHistorian** [comment]
this should be fixed in the next update
