### ISSUE TITLE
[FEATURE] Blink nofall

### ISSUE THREAD

**Issue by GAFUKIS** [RusherDevelopment/rusherhack-issues#1619]
**What feature would you like to be added.**

I have seen a nofall in 1.8 clients which blinks befare falling, and ending it after falling. I don't know if this feature would work in 1.20, but I think it would be a nice addition.

**Is your feature request related to a problem? Please describe.**

Nofall doesn't work in every server, and this would probably bypass (I don't really know, but it works really well in servers like hypixel)

**Comment by FluorideHistorian** [comment]
i dont believe this works on any anticheats that anarchy servers typically use

**Comment by GAFUKIS** [comment]
> i dont believe this works on any anticheats that anarchy servers typically use 

Aah ok, I really don't know, thanks for responding anyway
