### ISSUE TITLE
[BUG] HWID Bug

### ISSUE THREAD

**Issue by Nulled-Effect** [RusherDevelopment/rusherhack-issues#1625]
HWID Malfunction, downloaded the 1.20.2 client, went back to get it for 1.20.4 with the same installation .jar, and it said my HWID did not match

**To Reproduce**
Honestly im not sure how this happened, i just went back to try and get it for 1.20.4 and it failed on me.

**Other mods**
N/A, installation issue

**Expected behavior**
Be prompted to install another version of rusher

**Screenshots**
![Screenshot_2024-06-01_14_36_51](https://github.com/RusherDevelopment/rusherhack-issues/assets/97991351/95316c06-f31b-4f1a-ac94-2b7f50413a7b)

**Additional context**

**Comment by FluorideHistorian** [comment]
using sudo causes a hwid error

**Comment by Nulled-Effect** [comment]
> using sudo causes a hwid error

noted, thanks for the help

**Comment by FluorideHistorian** [comment]
my pleasure
