### ISSUE TITLE
[FEATURE] Axis Viewer

### ISSUE THREAD

**Issue by PappyVanPoodle** [RusherDevelopment/rusherhack-issues#1628]
**What feature would you like to be added.**
Provides a customizable line that you can see that follow all the axes. 
**Is your feature request related to a problem? Please describe.**
This makes it easier to find where you are going and makes it easy to pinpoint how far away you are from the nearest highway. It only shows up when you are a certain radius from the axis (which in my opinion should be customizable as well)
**Additional context**
It is a module on a Meteor addon called HighwayTools, which I found useful and using all the time despite it only appearing in such a niche addon.

![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/154875685/91277270-da87-4860-97f1-3a8c52a97cd3)

**Comment by John200410** [comment]
This would be a good setting to include in the Borders module

**Comment by FluorideHistorian** [comment]
this has been added in the next update under the borders module
