### ISSUE TITLE
Unable to add main account to alt manager

### ISSUE THREAD

**Issue by borrelliii** [RusherDevelopment/rusherhack-issues#1630]
When trying to add account to alt manager, going through all the website steps and allowing access, launcher does not receive verification to add login to alt manager. When trying to add another account, works fine, but for the main account, it fails to be added.

**To Reproduce**
trying to connect main account to alt manager

**Other mods**
Other mods don't seem to affect this

**Expected behavior**
Main account added without any issues

**Additional context**
any other account I had works except for this one.

**Comment by FluorideHistorian** [comment]
please open a support ticket in the discord
