### ISSUE TITLE
[Installer Grey On Wayland] 

### ISSUE THREAD

**Issue by Faraday22** [RusherDevelopment/rusherhack-issues#1631]
**Describe the bug**
The Rusher hack install way grey on wayland, link the whole java window doesn't show anything. I'm on swayWM

**To Reproduce**
Launch installer on wayland

**Expected behavior**
The installer to normal launch

**Screenshots**
[Link to IMG](https://imgur.com/a/eRkOupQ)

**Additional context**
To fix add this to .bashrc or .zshrc etc `export _JAVA_AWT_WM_NONREPARENTING=1` this will make the installer load as intended
I found this a while back but forgot to report this

**Comment by Faraday22** [comment]
This bug is probably exclusive to Linux, but I can't confirm

**Comment by John200410** [comment]
I'm not really sure if there is anything I can do about this, as its a bug in Java itself: https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing
