### ISSUE TITLE
[FEATURE] BaseFinder

### ISSUE THREAD

**Issue by rcpcn** [RusherDevelopment/rusherhack-issues#1640]
**What feature would you like to be added.**
Coordinate disabler for basefinder (distance module)

**Is your feature request related to a problem? Please describe.**
Maybe this thing will be good for streamers etc.

**Additional context**
.

**Comment by Lokfid** [comment]
Hello you can enable BaseFinder -> Logger -> Notification -> CensorCoords.
if i didn't understood you properly please re-open the issue
