### ISSUE TITLE
[BUG] I can't open the injector

### ISSUE THREAD

**Issue by xiaoxuanxuan2233** [RusherDevelopment/rusherhack-issues#1643]
I made sure I was using a VPN, and I also tried resetting the computer but the issue was not resolved, previous versions all worked but the new version did not.
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/110706011/b24eb900-2f96-4685-8f64-c05968fb3eea)

**Comment by John200410** [comment]
This is not the place to ask for support. Please contact support via email or in the DIscord.
