### ISSUE TITLE
Click Tp

### ISSUE THREAD

**Issue by Itsmaitiv** [RusherDevelopment/rusherhack-issues#1644]
Click TP: Teleports you to the block you click on, also there should be an option to set the distance.

https://cdn.discordapp.com/attachments/1256287901302390914/1256327513031049337/image.png?ex=66805dac&is=667f0c2c&hm=08caf1f5892f59a7848b18ce1b6b2d65ac932f24d46bb33b6a69f0622ce0b479&

**Comment by John200410** [comment]
I don't really think I will ever add this, it won't work on any server.
