### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by haristic** [RusherDevelopment/rusherhack-issues#1649]
game crashes whenever enabling flight

i enable flight on meteor and it occasionally crashes my game, i now use meteor and rusherhack together, but the game wouldnt crash whenever i just used meteor by iteself

i use meteor and sodium with rusherhack

the game shouldnt crash

**Comment by John200410** [comment]
I'm not sure what you want us to do about meteor's Flight crashing your game. Please report this to the developers of meteor

**Comment by John200410** [comment]
Or upload any crash log and we can check if its coming from meteor or from rusherhack
