### ISSUE TITLE
Automount bedmount add

### ISSUE THREAD

**Issue by Quinten5th** [RusherDevelopment/rusherhack-issues#1650]
Add an option in automount that sleeps in the bed every night. Untill the day timer kicks you out.

**Is your feature request related to a problem? Please describe.**
No, there are vanilla features with sleeping in a bed and afking. Would like to afk + sleep in bed every night.

**Additional context**
My guess its a simple add because after the sleep in bed no lines have to be made.

**Comment by FluorideHistorian** [comment]
this has been added in the next update
