### ISSUE TITLE
[FEATURE] Autodisconnect at coords

### ISSUE THREAD

**Issue by Its3rr0rsWRLD** [RusherDevelopment/rusherhack-issues#1652]
**What feature would you like to be added.**
An option to automatically log out when at or past certain coords

**Is your feature request related to a problem? Please describe.**
Makes it easier to afk travel

**Comment by FluorideHistorian** [comment]
AutoDisconnect -> Proximity -> Coordinates
*autodisconnect coordinates [x] [z]
or
Waypoints -> AutoDisconnect
