### ISSUE TITLE
ebounce gets you kicked off diagonal highways at high speeds[BUG] 

### ISSUE THREAD

**Issue by ICanNoot** [RusherDevelopment/rusherhack-issues#1655]
**Describe the bug**
When going faster than around 150-200kmh with ebounce, you will fly off the diag highway every hundred blocks or so. It's almost like hitting a block that's not there. Makes the highway unafkable because you have to be there to bring yourself back on the highway when you get kicked off.

**To Reproduce**
Steps to reproduce the behavior: turn on ebounce, turn off delay and turn on boost. At that high speed you will end up flying off.

**Other mods**
List other mods you are using (if any):

**Expected behavior**
Being able to ebounce on the highway without getting kicked off. 

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://www.youtube.com/watch?v=IJntlYji-dc)

**Additional context**
Can be fixed by disabling boost & enabling delay, however traveling the highway is much, much slower.

**Comment by FluorideHistorian** [comment]
disable the boost setting
this is an issue with 2bs anticheat and theres nothing we can do about it
