### ISSUE TITLE
[FEATURE] NEWCHUNKS recommendations

### ISSUE THREAD

**Issue by imakoda** [RusherDevelopment/rusherhack-issues#1656]
**What feature would you like to be added.**
Hello, I am here to recommend two things.
First when you activate NEWWCHUNKS with WATER MOTION mode and then activate the INVERT checkbox, it really doesn't work.
And second it would be nice if the NEWCHUNKS with WATER MOTION would update the chunks before, it is uncomfortable that the chunks pixels are painted at the same speed that the player is flying. The NEWCHUNKS addon meteor-rejects works very well, and updates the chunks even in front of the player, I hope they can implement it, it is uncomfortable to activate the freelook to be able to visualize the terrain well while using the NEWCHUNIKS

**Comment by John200410** [comment]
NewChunks has been updated
