### ISSUE TITLE
[BUG] extra tooltips shulkers

### ISSUE THREAD

**Issue by AlsoShy** [RusherDevelopment/rusherhack-issues#1664]
**Describe the bug**
Extra tooltips Shulkers dont render anything in the shulker when you hover over

**To Reproduce**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/120041780/f88b4640-44a3-471b-900a-5506fbe3eca4)

**Other mods**
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/120041780/060fda0a-f81a-403d-90c5-f6b45bfd081b)

**Expected behavior**
to show what is inside the shulker

**Screenshots**
![Screenshot 2024-07-10 132325](https://github.com/RusherDevelopment/rusherhack-issues/assets/120041780/02e8b913-727a-4a8e-a1dd-d11349c768e9)

![Screenshot 2024-07-10 132333](https://github.com/RusherDevelopment/rusherhack-issues/assets/120041780/37137a41-eb74-4a4e-8601-222a984020fe)

**Comment by 5HT2** [comment]
this is an issue with the server you are playing on, it's not sending shulker data. not an issue with the module itself

**Comment by 5HT2** [comment]
shulker tooltips have caching support, so if you open the shulker and then break -> pick up again it should remember the contents

**Comment by John200410** [comment]
It looks like the server you are playing on is on a lower/higher version of the game than the version you are playing on. There isn't much I can do about this

**Comment by John200410** [comment]
Using the ViaFabricPlus mod with the version set to the server version should fix it.
