### ISSUE TITLE
[No panorama)

### ISSUE THREAD

**Issue by Faraday22** [RusherDevelopment/rusherhack-issues#1665]
**What feature would you like to be added.**
The ability to remove the custom panorama, on menu screen

**Is your feature request related to a problem? Please describe.**
I have a shit laptop and sometimes if I open minecraft with many mods my laptop becomes a jet engine stalling in the air

**Additional context**
I don't think theirs a setting for it or way to turn it off but if their is lmk pls

**Comment by 5HT2** [comment]
you can turn this off Client → MainMenu settings

**Comment by Faraday22** [comment]
My apologies thank you
