### ISSUE TITLE
[FEATURE] FOV slider for Killaura

### ISSUE THREAD

**Issue by AkiyamaMizukiAlt** [RusherDevelopment/rusherhack-issues#1677]
**What feature would you like to be added.**
Adding a FOV slider to the Killaura option. This helps with slightly stricter anarchy anticheats.

**Comment by AkiyamaMizukiAlt** [comment]
It would also just be very nice customizeability to have for private SMPs and the like

**Comment by FluorideHistorian** [comment]
im not sure what anarchy servers this is needed on but im pretty sure just lowering the rotation speed would also work
