### ISSUE TITLE
[BUG] command server isnt listed on help

### ISSUE THREAD

**Issue by kybe236** [RusherDevelopment/rusherhack-issues#1680]
**Describe the bug**
if you type help in the console window the command server is not listed

**To Reproduce**
open minecraft with rusher
open the Console Window
type help in it and press enter

**Expected behavior**
an list of all command including server to be listed

**Screenshots**
![image](https://github.com/user-attachments/assets/a45da37c-8e81-421c-8219-d913aaa5894f)

**Comment by FluorideHistorian** [comment]
server is an alias for the connect command
