### ISSUE TITLE
[FEATURE] visual range ignore friends

### ISSUE THREAD

**Issue by SlyCrackz** [RusherDevelopment/rusherhack-issues#1681]
**What feature would you like to be added.**
An option for the PvpInfo module, so that VisualRange can ignore friends on rusher friendlist.

**Is your feature request related to a problem? Please describe.**
I am annoyed when it pings me and alerts me when I am hanging with my friends. I would like to only be notified when an a neutral player or enemy player is near.

**Comment by FluorideHistorian** [comment]
this has been added in the next update
