### ISSUE TITLE
[FEATURE] AutoTool Attacking PrioritizeSwords

### ISSUE THREAD

**Issue by lilnarco** [RusherDevelopment/rusherhack-issues#1682]
**What feature would you like to be added.**

Create a PrioritizeSwords option for autotool. 

**Is your feature request related to a problem? Please describe.**

Currently, autotool's attacking setting seems to prioritize only the highest damage weapon. There is no option to prioritize a sword over an axe, meaning players are forced to either remove the sharpness enchantment from the axe or remove the axe from their inventory.

**Comment by FluorideHistorian** [comment]
it works by multiplying attack damage by attack speed

**Comment by FluorideHistorian** [comment]
are you on 1.21

**Comment by lilnarco** [comment]
> are you on 1.21

This happens on both 1.20.6 and 1.21

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
