### ISSUE TITLE
[BUG] vclip not teleporting more than 10 blocks on a server without anticheats

### ISSUE THREAD

**Issue by EnardDev** [RusherDevelopment/rusherhack-issues#1689]
**Describe the bug**
Can't vclip downward or more than 10 blocks with a server without anticheats

**To Reproduce**
*vclip 100

**Other mods**
Meteor

**Expected behavior**
Teleport me downward or more than 10 block upward

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
