### ISSUE TITLE
[FEATURE] Module that tracks players with elytra making it easier to sword people in air

### ISSUE THREAD

**Issue by Cooliokid** [RusherDevelopment/rusherhack-issues#169]
**What feature would you like to be added.**
If somebody is just wasping in a fight a way to get rid of them is by going up and sword if them but that annoying because they can just fly around dodging me if there was a feature that just followed them as close as possible so I can actually sword them continuously 

**Is your feature request related to a problem? Please describe.**
I’m annoyed when people wasp and this would make it easier to get rid of them

**Comment by John200410** [comment]
Might do this

**Comment by FluorideHistorian** [comment]
assuming the server with this meta even still exists
would make more sense as a plugin
