### ISSUE TITLE
[FEATURE] SeedMapper Implementation

### ISSUE THREAD

**Issue by EnardDev** [RusherDevelopment/rusherhack-issues#1691]
**What feature would you like to be added.**
A overlay that allows to compare the natural seed terrain with the actual terrain

Example : https://github.com/xpple/SeedMapper

**Additional context**
Would be a powerfull module for basehunting  allowing to find irregulaties in the nether terrain

**Comment by FluorideHistorian** [comment]
duplicate of #298 and probably better as a plugin
