### ISSUE TITLE
[BUG] Autodisconnect - Y Value

### ISSUE THREAD

**Issue by Blizzen** [RusherDevelopment/rusherhack-issues#1704]
**Describe the bug**
Autodisconnect - Y value is triggered whenever you reconnect to 2b2t from the queue server, regardless of the Y value your character is at

**To Reproduce**
1.) fly to Y > 500
2.) set Autodisconnect Y value to > 65 (Y value of queue server)
3.) disconnect. Upon reconnecting, you will sit through queue as normal
4.) When you rejoin 2b2t from the queue server, you will be disconnected

**Other mods**
N/A

**Expected behavior**
You are either expected to:

a.) Disconnect instantly when you connect to queue (bad)

b.) Don't disconnect at all while reconnecting to 2b2t (good)

**Screenshots**
![image](https://github.com/user-attachments/assets/43e87184-3fc0-46a4-b16a-63f1ef470227)

**Additional context**
The disconnect does not happen because the Y value in the queue server is 65. It appears to happen because as you connect to the main 2b2t server proxy, your Y value is desynchronously updated. This would explain why the disconnect is not instantly when you rejoin the queue server.

**Comment by FluorideHistorian** [comment]
i believe this has been fixed in the next update
reopen if not
