### ISSUE TITLE
DoubleBreak  [BUG] 

### ISSUE THREAD

**Issue by FastPlays08** [RusherDevelopment/rusherhack-issues#1706]
**Describe the bug**

1. You have to select three blocks and wait for the first one to break before DoubleBreak kicks in
2. When DoubleBreak is enabled in FastBreak > Queue with rotations enabled the client rotates to the first block broken and then resets to previous rotation 

**To Reproduce**
Steps to reproduce the behavior (for the second bug):

Click on three blocks  with the following FastBreak config and watch the rotations

**Expected behavior**

1. Once you select a second block it immediately starts double-mining it without waiting for the first to break
2. Once one of the double mining blocks is broken it should rotate to the other and only reset when both are broken

**Screenshots**
FastBreak config below:
![image](https://github.com/user-attachments/assets/a9c3d9e4-5ec0-41ad-b88b-a0a8e5edb367)

**Comment by FluorideHistorian** [comment]
it now rotates to the second block in the next update
