### ISSUE TITLE
[FEATURE] Gold Auto Armor

### ISSUE THREAD

**Issue by Osmobyte** [RusherDevelopment/rusherhack-issues#1707]
**What feature would you like to be added.**
I think there should be a feature within AutoArmor to allow for Gold Armor to be worn for Piglin Deterence while traveling.

**Additional context**
I travel a lot, so Auto Armor allows me to replace Elytra automatically without worry. However, in order to adorn my gold leggings that I use for travel, I have to put my netherite pants into a shulker box so that my Auto Armor doesn't replace the gold leggings.
Anyhow, thanks so much, take care

**Comment by John200410** [comment]
There’s currently a plugin with this functionality: https://github.com/ShayBox/ShaysRusherTweaks

I’m not sure if this is something I’d want to add directly to rusherhack
