### ISSUE TITLE
[BUG] Stair Orientation with the module Sprint on.

### ISSUE THREAD

**Issue by ItzMarni** [RusherDevelopment/rusherhack-issues#1709]
**Describe the bug**
When you have  the module sprint on, placing stairs puts them in weird orientation, attached a video below showcasing it with the module on/off

**To Reproduce**
1. turn sprint on
2. place stairs

**Other mods**
Whole bunch of them, not affecting this though

**Expected behavior**
Same behavior with sprint off when its on

**Screenshots**
Attached

**Additional context**
works fine with meteors sprint module 

ok github very stupid, cant upload files more than 10mb here is a yt link: https://www.youtube.com/watch?v=ojUasCLU_6U

**Comment by FluorideHistorian** [comment]
same issue as #1637
disable strict if not on 2b otherwise disable omnidirectional
