### ISSUE TITLE
[BUG] GUI Size Pinned Windows

### ISSUE THREAD

**Issue by GarlicRot** [RusherDevelopment/rusherhack-issues#1711]
**Describe the bug**
When GUI size is different than 2 pinning a window changes the position/size of the pinned window sometimes off screen 

**To Reproduce**
change gui size and pin window

**Other mods**
List other mods you are using (if any):

**Expected behavior**

**Screenshots**
http://garlic.tulipterminal.com/SeRU1/miVUXoYo09.png
https://streamable.com/4p25ar

**Additional context**

**Comment by John200410** [comment]
Fixed in the next update
