### ISSUE TITLE
[BUG]  changing ClickGUI scale makes UI off-centered

### ISSUE THREAD

**Issue by Jamster707** [RusherDevelopment/rusherhack-issues#1713]
**Describe the bug**
when changing the clickGUI scale, the clickgui becomes off-center resulting in half of the modules not showing up on screen.

**To Reproduce**
Change clickGui scale

**Other mods**
None

**Expected behavior**
when changing the ClickGui scale, it should keep centered on the screen, allowing all modules to be used.

**Screenshots**
![image](https://github.com/user-attachments/assets/35551960-29d6-40ba-a3f4-1e1c511efdb1)

**Additional context**
i am encountering this issue on my 4K monitor, which makes the text  very small with the clickgui scale at 1.

**Comment by John200410** [comment]
Hi, can you please try the `*clickgui reset` command? It should reset the positions

**Comment by Jamster707** [comment]
> Hi, can you please try the `*clickgui reset` command? It should reset the positions

thank you, that worked :)
