### ISSUE TITLE
[BUG] Modules list not appearing

### ISSUE THREAD

**Issue by Kuchikun500** [RusherDevelopment/rusherhack-issues#1714]
![imagen_2024-08-23_220903870](https://github.com/user-attachments/assets/34565127-4ae0-45a2-a66b-0768b9cca13a)
Player, Render, World and Client list not appearing

**Comment by John200410** [comment]
Hello,

Can you please try using the command: `*reset clickgui`
It looks like those panels may be off-screen.

**Comment by Kuchikun500** [comment]
It worked! Ty John

**Comment by John200410** [comment]
Glad I could help! In the future please ask support questions in the discord server, this issue tracker is not for support

**Comment by Kuchikun500** [comment]
Alr boss
