### ISSUE TITLE
[BUG] Mace is not used by Aura

### ISSUE THREAD

**Issue by z3nghoul** [RusherDevelopment/rusherhack-issues#1733]
**Describe the bug**
Mace is not used by Aura if i dont disable weapon check. 

**To Reproduce**
Try to use Mace with and without weapon check

**Other mods**
-

**Expected behavior**
Mace is a weapon so it must be used by Aura with enabled weapon check

**Screenshots**
-

**Additional context**
-

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
