### ISSUE TITLE
[BUG] Require Pickaxe on AutoMine doesnt work 

### ISSUE THREAD

**Issue by kybe236** [RusherDevelopment/rusherhack-issues#1740]
**Describe the bug**
Require Pickaxe on AutoMine doesnt work (Mines always)

**To Reproduce**
get into an situation where automine would mine
notice that it mines without having pickaxe in hand

**Expected behavior**
It not mining except if i have an pickaxe in my hand

**Comment by FluorideHistorian** [comment]
this has been fixed in the next update
