### ISSUE TITLE
[BUG] Autodisconnect with totem check only disconnects when there are no totems left even if threshold value is >0

### ISSUE THREAD

**Issue by ledad1337** [RusherDevelopment/rusherhack-issues#1745]
**Describe the bug**
Autodisconnect with totem check only disconnects when there are no totems left even if threshold value is >0

**To Reproduce**
Enable autodisconnect health totemcheck set threshold value to anything >0 and pop all your totems

**Expected behavior**
Supposed to disconnect when number of totems in inventory is at threshold value.

**Comment by FluorideHistorian** [comment]
this should be fixed in the next update
