### ISSUE TITLE
[FEATURE] AutoArmorBypass for ElytraFly

### ISSUE THREAD

**Issue by Cheetosticksareawesome** [RusherDevelopment/rusherhack-issues#1754]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

This (sub)feature of ElytraFly would make it so that when you toggle ElytraFly it will turn ElytraPriority on in AutoArmor
and when you toggle off ElytraFly it will toggle off ElytraPriority in AutoArmor.

**Is your feature request related to a problem? Please describe.**

No This feature is more QOL it is possible to do with a macro

**Additional context**

**Comment by FluorideHistorian** [comment]
*macro create elytraprio <key>
*macro add elytraprio autoarmor elytrapriority
