### ISSUE TITLE
[BUG] Using 1.12.2, can't join multiplayer servers or crashes

### ISSUE THREAD

**Issue by 15ggd** [RusherDevelopment/rusherhack-issues#1763]
**Describe the bug**
Using MultiMC,  I installed RusherHack and Forge into the instances folder, whenever i load into a world, the game crashes.
**To Reproduce**
1. Install MultiMC
2. Make a new instance with version 1.12.2
3. Use RusherHackInstaller to install RH into the mods folder ( i chose no baritone)
4. Install Forge
5. Join server 
6. Crash
**Other mods**
List other mods you are using (if any):
none
**Expected behavior**
join the server like normal
**Screenshots**

**Additional context**

**Comment by 15ggd** [comment]
update legit RIGHT AFTER i made the bug, now it just crashes when i open it

**Comment by John200410** [comment]
Hello,
Help with rusherhack should be asked in the discord server. Please only use the issue tracker for reporting bugs and suggesting features.
