### ISSUE TITLE
[BUG] NoFall [legit] uses signs, trapdoors, pistons etc 

### ISSUE THREAD

**Issue by CrowSt** [RusherDevelopment/rusherhack-issues#1766]
**1. NoFall with mode "Legit" uses blocks, which couldn't help to prevent fall damage, for example signs and trapdoors.
2. It doesn't place a block (or a water bucket) in 100% of times -> https://imgur.com/BTQqJPq
3. It doesn't grab water back after falling
4. It can use doors! But he clicks 2 times, it opens the door and then Steve misses the clutch**

**To Reproduce**
- Enable NoFall with mode "Legit"
- Take in the hotbar any sign, any trapdoor or piston, buttons, pressure plates, saplings, CACTUS OR WITHER ROSE, sea pickles, etc...
- Jump high! And fall back down!

**Other mods**
It works with and without mods

**Expected behavior**
Calculate velocity to place a water bucket 1 block further, where Steve is going to fall, but not exactly under his feet (if he doesn't fall straight down) -> https://imgur.com/wHB8n1P
We can even place 2 blocks instead of one! -> https://imgur.com/TUVfTod

**Comment by John200410** [comment]
These bugs have now been fixed in the next update
