### ISSUE TITLE
[FEATURE] Throwing items in the position of freecam

### ISSUE THREAD

**Issue by reizi74** [RusherDevelopment/rusherhack-issues#1767]
https://github.com/user-attachments/assets/aea7639b-f545-4fde-89ca-c03b030bad05

https://github.com/user-attachments/assets/27bb2d80-74a2-42c1-92f1-216d2b0190ca

Don't know how, just informing that it is a thing in some private client

**Comment by John200410** [comment]
This looks like a bug with that client's Freecam. This would not work on any server with an anticheat.
