### ISSUE TITLE
[FEATURE] I want to create a new feature called burrow

### ISSUE THREAD

**Issue by JadeNight2131** [RusherDevelopment/rusherhack-issues#1776]
**What feature would you like to be added.**
Burrow: Automatically places a block under your feet and lets you be in that block, which functions much like "phase".

**Is your feature request related to a problem? Please describe.**
Burrow: Automatically places a block under your feet and lets you be in that block, which functions much like "phase".

**Additional context**
![屏幕截图 2024-10-20 170314](https://github.com/user-attachments/assets/29ba3f87-94d3-43fd-8958-af5065a77c51)
![屏幕截图 2024-10-20 170334](https://github.com/user-attachments/assets/3092e952-2d55-4910-a904-548dc6b63af9)

**Comment by Ji-Wu-0507** [comment]
And Add **Burrow ESP**

**Comment by FluorideHistorian** [comment]
the burrow module is SelfBlock

please open a separate issue explaining what burrow esp is

**Comment by JadeNight2131** [comment]
> the burrow module is SelfBlock
> 
> please open a separate issue explaining what burrow esp is

The burrowesp is "when someone burrowed, a red shade will cover the block"
![Uploading 屏幕截图 2024-11-07 205252.png…]()

**Comment by JadeNight2131** [comment]
> the burrow module is SelfBlock
> 
> please open a separate issue explaining what burrow esp is

The burrowesp is "when someone burrowed, a red shade will cover the block"
![屏幕截图 2024-11-07 205252](https://github.com/user-attachments/assets/049d2aec-9829-4c92-ab60-ee195ea11412)
