### ISSUE TITLE
[FEATURE] Strict AntiHunger logic for specific servers

### ISSUE THREAD

**Issue by 0CCULTIST** [RusherDevelopment/rusherhack-issues#1789]
**What feature would you like to be added.**
AntiHunger causes lagback while in water on certain anarchy servers such as Constantiam. Simply disabling itself internally would work, but maybe there's a better way. Could be in a "strict" setting.

**Comment by FluorideHistorian** [comment]
> *antihunger spoofsprint false

should fix it until next update but tell me if it doesn't

**Comment by 0CCULTIST** [comment]
> > *antihunger spoofsprint false
> 
> should fix it until next update but tell me if it doesn't

Is there a way to list all variables not in the GUI for modules?
