### ISSUE TITLE
[BUG] criticals don't work

### ISSUE THREAD

**Issue by gggghuuh** [RusherDevelopment/rusherhack-issues#1795]
**Describe the bug**
Criticals dont work.

**To Reproduce**
Aura rotate timing set to "sequential"
Antihunger turned on
Criticals on, mode "packet"

**Expected behavior**
whenever aura attacks, it doesn't crit. changing aura rotate timing to "vanilla" fixes this issue, OR turning antihunger off

weird

**Comment by gggghuuh** [comment]
sequential timing on aura also does not wait for the sword pullout animation with "weaponcheck" on

**Comment by FluorideHistorian** [comment]
> sequential timing on aura also does not wait for the sword pullout animation with "weaponcheck" on
this is intentional, you can hit with full damage the first tick you switch to a tool

**Comment by FluorideHistorian** [comment]
the issue with criticals has been fixed in the next update
