### ISSUE TITLE
[FEATURE]Add whispers preview for HUD

### ISSUE THREAD

**Issue by 0popbob** [RusherDevelopment/rusherhack-issues#185]
Add whispers preview for HUD 
do u remember Atom 0.7? this version have it and looks like this:
https://cdn.discordapp.com/attachments/775770062698053674/782031398126616586/Captura_de_Pantalla_2020-11-27_a_las_17.50.30.png

**Comment by John200410** [comment]
Thank you for the suggestion, I will add this when I rewrite ExtraChat in v1.2

**Comment by tycrek** [comment]
This would be cool to work while ExtraChat Hide is enabled. Also similar to #111

**Comment by FluorideHistorian** [comment]
i believe someone made a plugin which provides this functionality
