### ISSUE TITLE
[FEATURE] Better font settings

### ISSUE THREAD

**Issue by Cooliokid** [RusherDevelopment/rusherhack-issues#197]
**What feature would you like to be added.**
A configuration module similar to the baritone module that when toggled will enable or disable custom font for hud and the gui

**Is your feature request related to a problem? Please describe.**
It is annoying to change fonts and there isnt a way to make thing italic or bold and also change font size and other font settings

**Additional context**
Phobos has a amazing thing for this which also has a list of usable fonts 
![7c9d1b7274804ac86bf66dd1b6284adb](https://user-images.githubusercontent.com/69168012/101400106-4424cb80-3885-11eb-848d-a8904198d458.png)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by tycrek** [comment]
maybe a CustomFont window?

Tabs in the window:

- Font (includes a list of all the available fonts, with a search if possible)
- Settings (size, bold, italics, strikethrough, underline)
- Modules (?) (would list all the modules that can use CustomFont, with buttons to toggle CustomFont for the module and change the colour)

**Comment by FluorideHistorian** [comment]
font module exists as of v2.0
