### ISSUE TITLE
[FEATURE] ConnectSchedule

### ISSUE THREAD

**Issue by lomacanderson** [RusherDevelopment/rusherhack-issues#235]
**What feature would you like to be added.**
A module where you can select a time and server and it will automatically connect you to that server at that time if Minecraft is open, would mainly be used so you can connect to 2b2t queue while sleeping so when you wake up, you won't have to wait very long to get in game.

**Is your feature request related to a problem? Please describe.**
This is not related to a problem.

**Additional context**
No additional context

**Comment by John200410** [comment]
Neat idea. Not sure how many people would use this so I am going to consider this low-priority for now.

**Comment by jumboman32** [comment]
Try [this](https://github.com/tycrek/2queue2timer) out
