### ISSUE TITLE
[FEATURE] OpenAnywhere setting for Windows and ClickGUI

### ISSUE THREAD

**Issue by ItzDawnfall** [RusherDevelopment/rusherhack-issues#285]
**What feature would you like to be added.**
A setting under Windows and ClickGUI where you are able to toggle the ability to open the ClickGUI anywhere

**Additional context**
Requested by John

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This has been added in the next update in the Theme module
