### ISSUE TITLE
[FEATURE] EntityList blacklist

### ISSUE THREAD

**Issue by ScubaSteve1616** [RusherDevelopment/rusherhack-issues#290]
I like having the entities list on, but it shows all instances of say itemframes, cows, sheep,, etc. It would be nice if we could blacklist certain entities so they wouldn't show up in the list

**Comment by John200410** [comment]
Thank you for the suggestion. I will add a Mode setting.

**Comment by FluorideHistorian** [comment]
i think it was updated at some point and works via whitelist currently
is a blacklist desirable?

**Comment by FluorideHistorian** [comment]
closed in favor of #702
