### ISSUE TITLE
[FEATURE] SeedOverlay

### ISSUE THREAD

**Issue by myguybeefcake** [RusherDevelopment/rusherhack-issues#298]
This video explains the feature I would like added perfectly https://youtu.be/9fmgeYiP6Sg.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by jumboman32** [comment]
This doesn't exist yet.

**Comment by John200410** [comment]
Unlikely that this will ever be added due to the new custom chunk generation on 2b2t
