### ISSUE TITLE
[FEATURE] Bookbot

### ISSUE THREAD

**Issue by Lavacasted** [RusherDevelopment/rusherhack-issues#361]
**What feature would you like to be added.**
Bookbot. For example, forgehax bookbot (to create dupe books and ban books), or maybe producking a big amount of books for a group of people at an event (fight club, party events)  etc.

**Is your feature request related to a problem? Please describe.**
Nope. Its just a feature request.

**Additional context**
https://i.ytimg.com/vi/2iW-kGvEKQU/maxresdefault.jpg
Something like this...

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by FluorideHistorian** [comment]
there is now a plugin which provides this functionality
