### ISSUE TITLE
[FEATURE] Speed "jump" mode

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#483]
**What feature would you like to be added.**

Similar to Strafe but just vanilla jumping. Better for AFK than Strafe because Strafe can trigger lagbacks

**Comment by 2b2t-server** [comment]
Great suggestion that would be useful for walking in the highways if you have food.

**Comment by ItzDawnfall** [comment]
> Great suggestion that would be useful for walking in the highways if you have food.

Speed > Strafe

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by FluorideHistorian** [comment]
there is now an autojump setting is sprint
