### ISSUE TITLE
[FEATURE] BlockTweaks "block lock"

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#496]
**What feature would you like to be added.**

Would keep breaking the current in-progress block even when looking at a different block.

Without it (vanilla gameplay):

1. start mining block
2. Look at other block while mining
3. Mining switches to new block

With it:

1. Start mining block
2. look at other block while mining
3. continues mining previous block until it is broken

**Comment by John200410** [comment]
Thank you for the suggestion.
