### ISSUE TITLE
[FEATURE] Delete friends with delete/backspace key

### ISSUE THREAD

**Issue by robert40c** [RusherDevelopment/rusherhack-issues#53]
**What feature would you like to be added.**
Make it so you can click delete/backspace on your keyboard for friends.

**Is your feature request related to a problem? Please describe.**
In the windows, make it so you can simply click delete/backspace on your keyboard instead of right clicking and deleting. Also you could make it so + key will bring the option to add a friend. You could also do the same on the alt manager.

**Additional context**

**Comment by John200410** [comment]
This was implemented when Windows were added to v2.0
