### ISSUE TITLE
[FEATURE] "own mobs" setting to aura

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#530]
**What feature would you like to be added.**
own mobs setting- wouldnt attack entities you own for example horses or dogs if you have this disabled 

**Is your feature request related to a problem? Please describe.**
yes aura targets even entities you are riding right now but that got fixed in next update and i can only imagine i have aura on and it starts attacking my horse as soon as i get off it

**Comment by John200410** [comment]
I will add an "IgnoreTamed" setting

**Comment by FluorideHistorian** [comment]
this has been added in v2.0
