### ISSUE TITLE
[FEATURE] sand phase that doesn’t change y level

### ISSUE THREAD

**Issue by bstar16** [RusherDevelopment/rusherhack-issues#537]
sand phase except your y level isn’t effected meaning you only phase horizontally and stay on the same y level the boat was placed on, this can be useful for where boatfly is parched because this makes phase work without having to use boatfly

**Comment by bstar16** [comment]
edit: it would make it so you don't phase through the floor so either you would add a floor option to sand mode or make sand not go through the floor and then make a no clip mode that fully phases

**Comment by John200410** [comment]
I will add a setting to ignore the block below you

**Comment by FluorideHistorian** [comment]
sand phase doesn't change your y level as of v2.0
