### ISSUE TITLE
[BUG] Trajectories do not show up for item on offhand

### ISSUE THREAD

**Issue by browsky300** [RusherDevelopment/rusherhack-issues#554]
**Describe the bug**
When holding a bow/ender pearl in my offhand, the trajectory dissappears.

**Expected behavior**
The trajectory of the item is visible when holding it on your offhand.

**Screenshots**

https://i.imgur.com/sWYJL1o.png
https://i.imgur.com/N90MJkX.png

**Comment by John200410** [comment]
Thank you for reporting this.

**Comment by browsky300** [comment]
😶

**Comment by FluorideHistorian** [comment]
this has been fixed in v2.0
