### ISSUE TITLE
[FEATURE] anticrysral 

### ISSUE THREAD

**Issue by Tux8068** [RusherDevelopment/rusherhack-issues#564]
Places pressure plates under crystals to not take damage, this is perfect of 2b2t due to its slow crystal aura speed and the minimum existance ticks of 4, there should be a setting to place pressure plates only if the crystal does x damage to you
(konas anticrysral works amazingly on 2b2t)

**Comment by y4ndex1** [comment]
xenon skid

**Comment by Badinek** [comment]
> xenon skid

you mean 1.8 client youtube tutorial and 51 stunning letter k logo ideas

**Comment by y4ndex1** [comment]
you good badinek? anticrystal was originally made in xenon and konas pasted it as always

**Comment by Badinek** [comment]
> you good badinek? anticrystal was originally made in xenon and konas pasted it as always

yes i meant that on konas what else

**Comment by ProfKambing** [comment]
yandex has no proofs kek

**Comment by jumboman32** [comment]
poor mans self trap 👎

**Comment by John200410** [comment]
Thank you for the suggestion.
