### ISSUE TITLE
[FEATURE] LagDetector Movement Halt Option

### ISSUE THREAD

**Issue by Jesterrrr** [RusherDevelopment/rusherhack-issues#581]
**What feature would you like to be added.**
An option to LagDetector were it stops your movement when it detects lag.

**Is your feature request related to a problem? Please describe.**
To prevent possible kicks on 2b2t when lag happens and you continue to travel (Example AFK travelling in the nether highways)

**Additional context**
Make it priority over any other movement hacks so they won't interfere.

**Comment by ShaderTheBlackKid** [comment]
"Make it priority over any other movement hacks so they won't interfere."
They. are. mods. not. hacks.

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by Jesterrrr** [comment]
> "Make it priority over any other movement hacks so they won't interfere."
> They. are. mods. not. hacks.

Better edit my post to correct that or else nobody would understand it D:

**Comment by John200410** [comment]
AutoWalk has a PauseOnLag setting
