### ISSUE TITLE
[FEATURE] ESP polish

### ISSUE THREAD

**Issue by Radiocabea** [RusherDevelopment/rusherhack-issues#624]
**What feature would you like to be added.**
On the ESP module, when you have the outline mode or shader mode selected for entities, the outline/shader around sheep is to their "body" and not to their wool, so it looks kinda strange. The same thing happens with Skeletal horses, the back of their neck gets the "hair" like normal horses even tho it doesn't have it, same with donkeys. The same happens with slimes. Skeletons have a problem with their outline around their head, the same with zombies, wither skeletons, husks, strays, zombie villagers.

Some other mobs have the outline a little bit wrong, such as bats, vexes, silverfishes, indicators, zombie pigmans, the different types of villagers.

Also, make it so when you approach Storages ESP, you can have an option that makes the ESP disappear (either outline, shader, box, or CSGO). You already have something similar to this on the ColorMode Distance.

**Is your feature request related to a problem? Please describe.**
It's not really a problem, but it would make the client more polished!

**Additional context**
I'll not include all of the mobs mentioned above, but if you need me to, ill attach the mobs I've mentioned and what I think is wrong with them! Anyways, here are 3 examples.

![134](https://user-images.githubusercontent.com/20341203/114446370-118b3680-9bc9-11eb-93f2-00073ef5875b.png)
![135](https://user-images.githubusercontent.com/20341203/114446377-13ed9080-9bc9-11eb-9ad2-7c3569c0b34f.png)
![136](https://user-images.githubusercontent.com/20341203/114446382-151ebd80-9bc9-11eb-994e-8eaeeb2e236e.png)

**Comment by John200410** [comment]
This was done because rendering the layers with Outline ESP caused a lot of rendering issues. I will probably be able to fix this for Shader ESP though.

**Comment by FluorideHistorian** [comment]
outline mode is deprecated and i assume shader fixed this
