### ISSUE TITLE
[FEATURE] EntityList for storages

### ISSUE THREAD

**Issue by Tux8068** [RusherDevelopment/rusherhack-issues#627]
Make it so you can see x amount of chests, in your stash as well, make a "chest" setting thst will say "x amount of chests I.E 300

**Comment by tycrek** [comment]
I'd opt for this to be a separate "Storages" HUD module. Could list chests, echests, shulks, furnaces, trapped chests, all their minecart variants, etc. All individually toggleable ofc

**Comment by browsky300** [comment]
> 
> 
> I'd opt for this to be a separate "Storages" HUD module. Could list chests, echests, shulks, furnaces, trapped chests, all their minecart variants, etc. All individually toggleable ofc

Yeah, this would be really useful, especially for ender chests and shulkers.

**Comment by John200410** [comment]
Thank you for the suggestion. I will probably call it TileEntityList

**Comment by FluorideHistorian** [comment]
this is essentially DubCounter
