### ISSUE TITLE
[FEATURE] use gaussian blur

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#646]
**What feature would you like to be added.**

Gaussian blur is much sexier

Current blur at strength 5:
![image](https://user-images.githubusercontent.com/29926144/114804573-bd19bf80-9d5e-11eb-9ded-252946e6b41c.png)

Gaussian blur:
![rhblur](https://user-images.githubusercontent.com/29926144/114804454-89d73080-9d5e-11eb-82d0-f882dc969954.png)

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This was added in v2.0
