### ISSUE TITLE
[FEATURE] Item highlight

### ISSUE THREAD

**Issue by HarryPotter42MC** [RusherDevelopment/rusherhack-issues#652]
**What feature would you like to be added.**
A module, which is just like ExtraTooltips -> ShulkerHighlight but with a customizable item list

**Additional context**
![shulkerhighlightsa](https://user-images.githubusercontent.com/82435253/114908032-fa905280-9e1b-11eb-976f-b976c2825a31.png)

**Comment by tycrek** [comment]
+1, I would like this as well

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by John200410** [comment]
This is possible using ExtraChests's search feature
