### ISSUE TITLE
[FEATURE] Auto Farm

### ISSUE THREAD

**Issue by Overheadcams** [RusherDevelopment/rusherhack-issues#679]
**What feature would you like to be added.**
Add an auto farm bot that automatically harvests mature farm blocks like wheat and carrots and replaces them with their corresponding seeds to be regrown on the same block.

**Is your feature request related to a problem? Please describe.**
I like to farm.

**Additional context**
Take Wurst's Auto Farm for example. basically like that.
![wurst](https://user-images.githubusercontent.com/73721705/115968365-7eb59a80-a4ec-11eb-92c5-42e033c6415d.PNG)

**Comment by jumboman32** [comment]
If you use baritone try `#farm `.

**Comment by Overheadcams** [comment]
ive never tried baritone. ill look at it

**Comment by John200410** [comment]
Thank you for the suggestion.

For now you can use Baritone but I do plan on writing an AutoFarm for RusherHack.

I will leave this open and close #337

**Comment by Ozynt** [comment]
Remember to add echest farmer. From #337

**Comment by Ozynt** [comment]
sorry

**Comment by FluorideHistorian** [comment]
baritone feature
