### ISSUE TITLE
[BUG]  rusher surround pushes you off block

### ISSUE THREAD

**Issue by jewbob** [RusherDevelopment/rusherhack-issues#683]
**Describe the bug**
surround pushes you off the block instead of centering you if you're on the edge

**To Reproduce**
use surround on a single block in the air near the edge of it
**Other mods**
future konas rh (dosen't effect this issue)

**Expected behavior**
pushes me into the center of the block im on, instead of another

**Screenshots**
https://medal.tv/clips/50581698/d13370zYSZ4f  clip is here showing what it does

**Additional context**
yala

**Comment by Mishi04** [comment]
config issue

**Comment by L-Nadav** [comment]
> config issue

You have brain issues

**Comment by John200410** [comment]
Thank you for reporting this.
