### ISSUE TITLE
[FEATURE] image esp

### ISSUE THREAD

**Issue by ghost** [RusherDevelopment/rusherhack-issues#686]
A module that overlays players with funny images. examle here

https://imgur.com/a/N9OhkcX

**Comment by Mishi04** [comment]
cock esp

**Comment by tescomealdeal** [comment]
could have a folder in the config folder to use your own images

**Comment by John200410** [comment]
Thank you for the suggestion.

**Comment by FluorideHistorian** [comment]
this has been added in v2.0
