### ISSUE TITLE
[FEATURE] message logger *plus only*

### ISSUE THREAD

**Issue by Tux8068** [RusherDevelopment/rusherhack-issues#722]
Could that be a plus feature only, I imagine this module to be a command + module, in the module you will have different modes I.E messages, whispers, friends (whispers/normal chat), 

To achieve this, it will use discord webhooks to paste these messages into a private server. This will be the use of webhooks! To set up a webhook link you would do something on the lines of *messagelogger <insert profile picture image> <webhook link> <webhook name>

In my opinion this IS a really useful module, it allows you to have your own bot sending messages through your own private discord, and maybe you can do something the other way round? If i type  !hi in discord it will send it using my minecraft account.

**Comment by ProfKambing** [comment]
you could use multimc log but pretty good idea

**Comment by Tux8068** [comment]
Multimc log is useless, the point of having it on discord is so you can go to the shops or soemthing and monitor

**Comment by ProfKambing** [comment]
buy ttrms then

**Comment by ProfKambing** [comment]
i think it has that feature

**Comment by ShaderTheBlackKid** [comment]
Just make a bot do this

**Comment by HarryPotter42MC** [comment]
> Just make a bot do this

wtf he requested a feature for rusherhack and you say he should code it himself???

**Comment by HarryPotter42MC** [comment]
> buy ttrms then

why would he buy it if he can get it in rusherhack

**Comment by system69-e** [comment]
why plus only?

**Comment by ProfKambing** [comment]
only for cool kids

**Comment by L-Nadav** [comment]
This already exists and works really well, it's a tiny mod. It would have taken you 60 seconds to google this and see it exists

**Comment by John200410** [comment]
Unlikely that this will ever be added
