### ISSUE TITLE
[BUG] ChatAppend Prefix has weird line

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#724]
**Describe the bug**

I set my ChatAppend to Prefix mode and the text to `/r`, message recipients see this: 
![image](https://user-images.githubusercontent.com/29926144/117219722-15bf0400-adc3-11eb-9dd1-3319b7458cc8.png)

**To Reproduce**

![image](https://user-images.githubusercontent.com/29926144/117220869-56b81800-adc5-11eb-9828-45835e9537c6.png)
![image](https://user-images.githubusercontent.com/29926144/117220879-5c156280-adc5-11eb-9c2a-600af8e4d7f8.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/29926144/117219722-15bf0400-adc3-11eb-9dd1-3319b7458cc8.png)

**Comment by FluorideHistorian** [comment]
this is now toggleable in v2.0
