### ISSUE TITLE
[FEATURE] better macros or scripts

### ISSUE THREAD

**Issue by catgirljenni** [RusherDevelopment/rusherhack-issues#751]
allow executing multiple commands with one macro
simple logic, if/else and stuff like checking if a module is toggled
storing variables in the macro so behaviour changes when you use it multiple times
the first one is really the only one i care about right now but the other two would be neat

**Comment by tescomealdeal** [comment]
you could make multiple macros n bind them to the same key

**Comment by jennifer-uwu** [comment]
there would be no way to control the order of execution

**Comment by John200410** [comment]
Unlikely that this will happen due to the rusherhack API becoming a thing soon
