### ISSUE TITLE
[FEATURE] anti void scaffold

### ISSUE THREAD

**Issue by catgirljenni** [RusherDevelopment/rusherhack-issues#752]
rubberbands you or toggles scaffold if you are about to fall into the void

**Comment by jumboman32** [comment]
Avoid > Void

**Comment by ProfKambing** [comment]
yo jumboman the avoid thing doesnt rubberbands you nor toggle scaffold. it isnt the same

**Comment by jennifer-uwu** [comment]
^^

**Comment by jumboman32** [comment]
> yo jumboman the avoid thing doesnt rubberbands you nor toggle scaffold. it isnt the same

It does rubberband you, it looks different from the old antivoid, but even Y=-0.01 will kill you instantly on 2b.

**Comment by HarryPotter42MC** [comment]
then make a void jesus wich is packetflying at y= 0.5

**Comment by Doogie13** [comment]
antivoid can just set void blocks to solid but it can also rubberband when below Y 0 which is more consistent often
