### ISSUE TITLE
[BUG] Scroll moves up after scrolling to top

### ISSUE THREAD

**Issue by hashalite** [RusherDevelopment/rusherhack-issues#758]
**Describe the bug**
If you have StrictScrollClamp disabled, it scrolls up slightly after scrolling to the top of a category.

**Screenshots**
https://user-images.githubusercontent.com/71229440/118348955-a8764600-b51b-11eb-80e8-8a2c3a7950cc.mp4

**Comment by John200410** [comment]
Fixed in v2.0
