### ISSUE TITLE
[FEATURE] hwid failed window text improvments

### ISSUE THREAD

**Issue by HarryPotter42MC** [RusherDevelopment/rusherhack-issues#759]
**What feature would you like to be added.**
The text should also say that you can ask for a hwid reset in #support on the discord and not just "on the website" because I dont know anywhere you can request it there,

**Is your feature request related to a problem? Please describe.**
I just think it would help people who are new to rusherhack

**Comment by FluorideHistorian** [comment]
there is a support email posted on the website

**Comment by FluorideHistorian** [comment]
discord not being listed is apparently intentional
