### ISSUE TITLE
[FEATURE] FreeLook FirstPerson Option

### ISSUE THREAD

**Issue by Krashgamer** [RusherDevelopment/rusherhack-issues#766]
**What feature would you like to be added.**
FreeLook: Toggle between FirstPerson and ThirdPerson

**Is your feature request related to a problem? Please describe.**
no, I just miss this feature in every other client :c

**Additional context**
Used to use it in Impact Client back in the days... https://www.youtube.com/watch?v=wtYt9fiwxzM

**Comment by jumboman32** [comment]
I like this idea a lot. If you add it can you make an option for it to be toggled on key hold like it is in Rust.

**Comment by Krashgamer** [comment]
There already is an option to switch between Toggle and Hold. You just can't switch to First Person.

**Comment by FluorideHistorian** [comment]
this has been added in v2.0
