### ISSUE TITLE
[FEATURE] ShulkerHighlight is bugged

### ISSUE THREAD

**Issue by HarryPotter42MC** [RusherDevelopment/rusherhack-issues#769]
**Describe the bug**
https://youtu.be/a9LYGwnp0Hk

**To Reproduce**
Enable ExtraTooltips -> SHulkerHighlight

**Other mods**
none that would do that

**Expected behavior**
it should be the same colour

**Screenshots**
https://youtu.be/a9LYGwnp0Hk

**Additional context**
https://youtu.be/a9LYGwnp0Hk

**Comment by FluorideHistorian** [comment]
reopen if still occurring in v2.0
