### ISSUE TITLE
[FEATURE] Autopilot: ElytraFly

### ISSUE THREAD

**Issue by Lavacasted** [RusherDevelopment/rusherhack-issues#773]
**What feature would you like to be added.**
AutoPilot for ElytraFly

**Is your feature request related to a problem? Please describe.**
No.

**Additional context**

basically if i want to fly to 1337 1337 i can type *autopilot travel 1337 1337 and it would fly there. 

Consider adding StrictPath for highway travel. Basically it only attempts to travel in between the highway guards and DistanceOverride where StrictDirection will disable when it is at a specific distance (lets say 100 blocks) from my destination.

**Comment by HarryPotter42MC** [comment]
its literally a thing lmfao look in #releases

**Comment by HarryPotter42MC** [comment]
sorry, miss understood it yes, great feature

**Comment by HermanGoring** [comment]
> sorry, miss understood it yes, great feature request

good lol.

**Comment by ShaderTheBlackKid** [comment]
You do understand that this would basically only work in the overworld and it would just go to like y level 250, face towards the destination and use boost mode automatic to go there and land

**Comment by HarryPotter42MC** [comment]
look at pyro autopilot for boatfly. maybe something like this for control efly

**Comment by FluorideHistorian** [comment]
for highway you can use autodisconnect coords
otherwise use the new baritone elytra thing
