### ISSUE TITLE
[FEATURE] Strafe speed : vanilla sprintjump replace 

### ISSUE THREAD

**Issue by thebruhmoment** [RusherDevelopment/rusherhack-issues#775]
**What feature would you like to be added.**
The only stable working speed module in most anarchy servers is strafe mode,
it would be great if there was an option to like
replace vanilla sprintjumping with strafespeed, so you dont have to enable it every time you want to sprint,
just jump/sprintjump and it'll be enabling/disabling automatically

**Comment by SoggyBacco** [comment]
groundstrafe is a thing, normal strafe is better tho

**Comment by thebruhmoment** [comment]
> groundstrafe is a thing, normal strafe is better tho

i imagine it more like on/off thing for regular speed, when you are jumping. i think that it is actually possible to make this using ahk script but it is bullshit

**Comment by jumboman32** [comment]
Can you please clarify how it would automatically be toggled?

**Comment by VoidBite1** [comment]
> Can you please clarify how it would automatically be toggled?

I think they mean like that it's activated if you hold space, kind of like how freelook works.

**Comment by Ozynt** [comment]
Hold binds is a thing. It can be binded to space like how normal jump works.

**Comment by VoidBite1** [comment]
> Hold binds is a thing. It can be binded to space like how normal jump works.

Its not a thing for the speed module tho.

**Comment by Ozynt** [comment]
It is

**Comment by VoidBite1** [comment]
> It is

How do you enable it for speed then, because I can't find the option.

**Comment by FluorideHistorian** [comment]
hold the key while binding
