### ISSUE TITLE
[FEATURE] Improve 1.13+ Placements

### ISSUE THREAD

**Issue by jumboman32** [RusherDevelopment/rusherhack-issues#810]
**What feature would you like to be added.**
Improve 1.13+ Placements for AutoCrystal.

**Is your feature request related to a problem? Please describe.**
It will place in a 1x1, then try to face place regardless of minimum damage.

**Comment by John200410** [comment]
Can you record this issue?

**Comment by FluorideHistorian** [comment]
i am unable to reproduce this

**Comment by FluorideHistorian** [comment]
AutoCrystal has been rewritten in v2.0
reopen if issue still persists
