### ISSUE TITLE
[FEATURE] Customizable time formats

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#819]
**What feature would you like to be added.**

For ExtraChat Timestamps and ExtraSign using the ISO8601 timestamp format, `YYYY-MM-DD hh:mm:ss`

![image](https://user-images.githubusercontent.com/29926144/120091906-59f4aa00-c0cc-11eb-9d24-77d48a96899f.png)

**Comment by tycrek-archive** [comment]
Damn this would be based

**Comment by FluorideHistorian** [comment]
this would be incredibly based

**Comment by John200410** [comment]
This has been added in the next update
