### ISSUE TITLE
[FEATURE] More Crosshair Options

### ISSUE THREAD

**Issue by SilverEyes1** [RusherDevelopment/rusherhack-issues#820]
What feature would you like to be added.
New option added to CSGO Crosshair which will allow you to move the crosshair vertical and horizontal

Additional context
Installed World Edit CUI recently and on the 1.12 version the chunk measurer interferes with the my custom cross-hair

![2021-05-30_01 51 44](https://user-images.githubusercontent.com/84293911/120094575-152e3a80-c0ef-11eb-919e-d9adef1ae359.png)

**Comment by John200410** [comment]
So you want to offset the position?

**Comment by FluorideHistorian** [comment]
i have added offset settings in the next update
