### ISSUE TITLE
[FEATURE] Beacon ESP

### ISSUE THREAD

**Issue by SilverEyes1** [RusherDevelopment/rusherhack-issues#865]
**What feature would you like to be added.**
A "ESP" feature to see how far the a Minecraft Beacons effects range. This would allow you to see the radius of the Beacons effect.

**Is your feature request related to a problem? Please describe.**
I want to plan how far a Beacon goes for my base planning.

**Comment by ProfKambing** [comment]
you know you can use ur eyes for that

**Comment by FluorideHistorian** [comment]
probably a good setting for rangecircle

**Comment by FluorideHistorian** [comment]
this has been added as a setting in the borders module
