### ISSUE TITLE
[FEATURE]More consistent Entityjesus

### ISSUE THREAD

**Issue by REALERvolker1** [RusherDevelopment/rusherhack-issues#869]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

Server is 2b2t.org

I would like to have some form of entityjesus that is more consistent than normal Rusherhack Jesus. Current Rusherhack jesus works amazingly unless you want to get back onto land, and sometimes it rubberbands like crazy. New Entityjesus would only work with entities, and I would imagine it somewhat like Impact's Entityjesus, where it bobs up and down in the water, and if you jump in from a height, it bobs you down (but the horse doesn't eject you) and it takes you back up. Current jesus doesn't do this very much, and when you do, it reverts to the rubberbanding problem. 

**Is your feature request related to a problem? Please describe.**

I am always frustrated by the fact I have to still have Impact installed just because of this one feature that it does better than Rusherhack, a paid client. I have asked for help about this on the discord, but the general consensus was that "it works", when it only works part of the time. This inconsistency really bothers me and my friend. I have talked to him about it and he is also having issues with it. Everyone I have talked to has needed another client installed because of this.

**Additional context**

**Comment by FluorideHistorian** [comment]
due to entity jesus being patched on 2b2t awhile ago now i will close this until someone can provide a server in which another clients entity jesus functions better than rusherhacks
