### ISSUE TITLE
[FEATURE] ExtraTooltips Improvements

### ISSUE THREAD

**Issue by jumboman32** [RusherDevelopment/rusherhack-issues#875]
**What feature would you like to be added.**
Shulker Color Texture Mode for Peek

**Additional context**
![javaw_jNVrGh7goq](https://user-images.githubusercontent.com/68603817/122808484-f446a880-d29a-11eb-9341-63a78da248b0.png)
![javaw_SpOevcgdnK](https://user-images.githubusercontent.com/68603817/122808495-f7da2f80-d29a-11eb-9abc-e444f74ec49f.png)

**Comment by John200410** [comment]
This has been added in v2.0
