### ISSUE TITLE
[BUG] jesus bug

### ISSUE THREAD

**Issue by NotJohnmcswag** [RusherDevelopment/rusherhack-issues#933]
jesus boost has a really small jump, instead of something like futures which jumps much higher

how do reproduce
use jesus

**Comment by FluorideHistorian** [comment]
how is this a bug

**Comment by NotJohnmcswag** [comment]
john said it was

**Comment by FluorideHistorian** [comment]
ah i see

**Comment by FluorideHistorian** [comment]
unable to reproduce in v2.0, reopen if still occurring
