### ISSUE TITLE
[BUG] ExtraChest Steal mode: Steals the saddle

### ISSUE THREAD

**Issue by Infisrael** [RusherDevelopment/rusherhack-issues#943]
**Describe the bug**
When trying to mount any rideable entity with extrachest steal mode on, it will steal also the saddle you are trying to mount on a entity

**To Reproduce**
1. Get a saddle
2. Try to mount it while having extrachest steal mode on
3. You are unable to put the saddle

**Other mods**
no

**Expected behavior**
Ignore the horse's inventory

**Screenshots**
None. 

**Additional context**
None.

**Comment by jumboman32** [comment]
Replicated and it works for mode steal and fill in all containers.

**Comment by John200410** [comment]
Should be fixed as of v2.0
