### ISSUE TITLE
[FEATURE] AutoEXP Improvements

### ISSUE THREAD

**Issue by ghost** [RusherDevelopment/rusherhack-issues#949]
**What feature would you like to be added.**

AutoEXP Improvements, Add an option to where you can hold your AutoEXP keybind for it to activate (rather than pressing to toggle)

Add an option to disable armor going into your xcarry slots

**Is your feature request related to a problem? Please describe.**.

No

**Comment by FluorideHistorian** [comment]
both of these things were added at some point
