### ISSUE TITLE
[FEATURE] Improvements and Fixes

### ISSUE THREAD

**Issue by jumboman32** [RusherDevelopment/rusherhack-issues#951]
**What feature would you like to be added.**

- Shorten spammer commands (*spammer file.txt)
- ~Fix FastBreak AutoSwitch setting not saving~
- AutoSurround and AutoWeb render slow down active placements on 2b2t.
- ~AutoSurround still tries placing under you and desyncs you on 2b2t.~
- AutoTrap and Holefiller are inconsistent
- ~AutoEat will get you kicked on 2b2t if you are looking at a container while it eats~
- Add an option to disable ElytraFly if you pop a totem
- ~Add an Entity Search IgnoreOwn/Riding option~
- ~NewChunks width~
- ~NewChunks inverse (oldchunks)~
- ~ExtraTab OnlyShow doesn't work~
- ~Add an option to display armor durability as a value like how normal tool durability is shown~
- ~Speed Average Time Setting not saving~
- ~FreeLook distance setting~
- ~EntityJesus causes animals to get stuck on 2b2t~
- AutoTool mining causes issues with FastBreak AutoSwitch (I think)
- Change settings with preset colors to be dropdowns so you don't have to click through (like setting a color for timestamps)

Most of these aren't significant enough to have their own issues.

**Comment by tycrek** [comment]
> ExtraTab OnlyShow doesn't work

Works fine for me, using any combination of Friends & Enemies. Make sure dropdown menu itself is also enabled, iirc it's a toggle too

![image](https://user-images.githubusercontent.com/29926144/126908555-fb3b442c-6125-495c-bf27-05137ba80150.png)

**Comment by John200410** [comment]
> AutoSurround still tries placing under you and desyncs you on 2b2t.

this has been fixed in the next update.

> AutoEat will get you kicked on 2b2t if you are looking at a container while it eats

this has been fixed in the next update.

> ExtraTab OnlyShow doesn't work

this is probably a client conflict.

**Comment by John200410** [comment]
> AutoTrap and Holefiller are inconsistent

Can you elaborate a little more on this?

**Comment by John200410** [comment]
> FreeLook distance setting

You can use ViewClip
