### ISSUE TITLE
[BUG] Gamemode spectator unable to spectate entities

### ISSUE THREAD

**Issue by REALERvolker1** [RusherDevelopment/rusherhack-issues#952]
**What feature would you like to be added.**
I would like a feature that let you go into spectator mode client-side. There could be a setting where your player just stands still where your view just goes into another player's, like spectator mode, and there could be a different setting for actually going into real spectator mode.

**Is your feature request related to a problem? Please describe.**
I wish Freecam let you spectate players by seeing their POV.

**Additional context**
basic spectator mode, could be useful ;)

**Comment by Doogie13** [comment]
this would be cool as a mode in freecam so if you middle click an entity it spectates it

**Comment by FluorideHistorian** [comment]
this should be able to be done with gamemode or gamemode + freecam but its bugged rn

**Comment by FluorideHistorian** [comment]
a spectate setting has been added to freecam
