### ISSUE TITLE
[FEATURE] arraylist improvements

### ISSUE THREAD

**Issue by SoggyBacco** [RusherDevelopment/rusherhack-issues#955]
more customization options such as alphabetical ordering and color coding

maybe metadata for more modules too
ex: AutoCrystal [dmg]

**Comment by tycrek** [comment]
I'd also like to customize which modules show metadata, and for some customize what data is being shown

**Comment by FluorideHistorian** [comment]
alphabetical ordering is possible
color coding duplicate of #1183 
autocrystal now has damage metadata option
