### ISSUE TITLE
[BUG] Autoweb bugs

### ISSUE THREAD

**Issue by thebruhmoment** [RusherDevelopment/rusherhack-issues#956]
**Describe the bug**
1) Autoweb rendering is not disabling even if it is set to disabled
2) Autoweb doesen't place webs in holes if there is no player nearby
**To Reproduce**
config:
    {
    "name": "AutoWeb",
    "toggled": false,
    "bind": "KEY_Q",
    "visible": true,
    "mode": "MACRO",
    "target": "HOLES",
    "autoswitch": "NORMAL",
    "webdistance": "4.3",
    "height": "1",
    "range": "4.5",
    "delay": "0.0",
    "ignoreownhole": "false",
    "rotate": "true",
    "render": "false",
    "color": "Rainbow:false,Color:-1688292"
  },

**Other mods**
future, optifine

**Expected behavior**
placing webs in holes even if no players nearby, when render disabled disabling render

**Screenshots**
https://www.youtube.com/watch?v=RzNieqevtYM

**Additional context**

**Comment by end41r** [comment]
Maybe you have something rendering webs in future

**Comment by FluorideHistorian** [comment]
>Autoweb doesen't place webs in holes if there is no player nearby
works as intended

**Comment by John200410** [comment]
Rendering bug fixed in v2.0
