### ISSUE TITLE
[FEATURE] Sprint jump scaffold wich stays on one height

### ISSUE THREAD

**Issue by HarryPotter42MC** [RusherDevelopment/rusherhack-issues#961]
**What feature would you like to be added.**
Ive just tried to sprint jump scaffold on build limit and it works perfectly fine so I thought it would be nice if you could hold down a key wich makes your scaffold stay on the same height and makes you able to sprint jump scaffold with would look cool and improve the speed

**Is your feature request related to a problem? Please describe.**
no

**Additional context**
no

**Comment by FluorideHistorian** [comment]
this has been added to v2.0
