### ISSUE TITLE
[FEATURE] few improvements

### ISSUE THREAD

**Issue by Badinek** [RusherDevelopment/rusherhack-issues#972]
so up until now i used abyss with rusher, but due to abyss taking up 4gb of my ram for no reason ( 🐀 ) i decided to ditch it and use only rusher- this is what you should improve

| Feature | Description | Status |
| :-----: | ----------- | ------ |
| SPEED STRAFE | make it not rubberband in 2x1 spaces (yes it doesnt rubberband with abyss strafe) make it sprint jump to SIDES even if ur crouching (rn if you try to crouch and jump to side at once its like the 4km/h vanilla jumping), make the strafe work with criticals module (already reported this in past, no criticals from any client work with rusher strafe) | | 
| CRITICALS BYPASS | they only work if you are standing still or walking, they dont work if you are sprinting though, at all. maybe make them cancel midair too so it gives vanilla criticals in case you are strafing? idk how it works | |
| DVD LOGO | we already talked about this in the discord, make something like customizable element that bounces on your screen in guis | **ALREADY DONE**
| |
| COORDINATES HUD ELEMENT | i guess this is just matter of preference but i hate how the current coords are like (X) (X other dimension) (Y) (Z) (Z other dimension), maybe make mode like in all other normal clients that is (X) (Y) (Z) (X Y Z other dimension) | |
| AUTOTOTEM/INVMOVE | rn the autototem is just complete garbage, fails even if you stand still so i guess improve it somehow | |
| SELFBLOCK | burrow fails a lot near walls/blocks so fix that | |
| PLAYER MODEL | the hud element thingy which displays your model, if you are in gui its looking in the top left corner for some reason instead of forward (doesnt matter if forward setting is enabled it happens either way) | **ALREADY DONE** |
| (new feature) HAND MINE | i actually dont know if rusher has this but i couldnt find it so ill just list it here, basically makes you able to mine blocks with your hand or other item other than pickaxe (the pickaxe needs to be in hotbar) | |
| LIQUID INTERACT | right now the liquid interact doesnt work if you are IN water, it does work on abyss so guess its possible | |
| (new feature) SKY COLOR | makes you able to change sky in all dimensions, **either different color (ALREADY DONE)** or just some picture | **ALREADY DONE** |
| SCAFFOLD | implement "groundstrafe" to the scaffold, it makes the movement better (future scaffold has this or atleast used to) | |
| SPEED GROUNDSTRAFE | make it cancel the speed module while shifting (right now its trying to sprint walk even while shifting causing rubberbands, same when you want to eat) | |**ALREADY DONE**
| AUTORECONNECT | add seconds/miliseconds delay slider on the disconnect screen so you can edit the delay without leaving the dc page, and make both slider and clickgui delay setting max 60/90 seconds because 30 is not enough- if you get the "connection lost" kick message you have to wait 60 seconds not 30 | 
| ELYTRAFLY | dont really know how to describe it but the lower your vertical speed is the lower the pitch you go diagonally is while pressing W + S/SPACE, i would like it to go in 45 degrees always and make vertical speed affect only how fast it will go | 

i may add more things to this list over time cause cant remember all the things right now

UPDATE: things that are already done have been highlighted with bold text, added scaffold, autoreconnect, elytrafly and groundstrafe suggestions

**Comment by martin010919** [comment]
Mega pog suggestions, the water interact bug is bother me too
+rep

**Comment by tycrek** [comment]
> (new feature) HAND MINE- i actually dont know if rusher has this but i couldnt find it so ill just list it here, basically makes you able to mine blocks with your hand or other item other than pickaxe (the pickaxe needs to be in hotbar)

I think this is the closest RH has:

![this](https://ass.rip/profuse-yellow-haunting-goral/direct)

> COORDINATES HUD ELEMENT

Optional preferably, I personally like RH's the best

**Comment by ProfKambing** [comment]
maybe john can make packetswitch for fastbreak

**Comment by John200410** [comment]
SkyColor has been added in the next update

**Comment by John200410** [comment]
> burrow fails a lot near walls/blocks so fix that

I added a Center setting to SelfBlock in the next update so that may fix it.

**Comment by John200410** [comment]
> PLAYER MODEL- the hud element thingy which displays your model, if you are in gui its looking in the top left corner for some reason instead of forward (doesnt matter if forward setting is enabled it happens either way)

This has been fixed in the next update.

**Comment by Badinek** [comment]
updated the issue, added few more things

**Comment by tycrek** [comment]
I made the unreadable list a much more readable table

**Comment by Badinek** [comment]
added AutoReconnect improvement suggestion

**Comment by Badinek** [comment]
added ElytraFly improvement suggestion

**Comment by John200410** [comment]
BouncingLogo has been added in the next update

**Comment by FluorideHistorian** [comment]
The liquidInteract suggestion has been addressed and will be released with v2.0

**Comment by FluorideHistorian** [comment]
The Criticals suggestion has been addressed and will be released with v2.0

**Comment by FluorideHistorian** [comment]
one suggestion per git issue please
