### ISSUE TITLE
[BUG] AutoWalk PauseOnLag does not work with entities (and on foot?)

### ISSUE THREAD

**Issue by tycrek** [RusherDevelopment/rusherhack-issues#973]
**Describe the bug**

PauseOnLag simply doesn't work. It has never worked with entities for me and I don't think it works when I'm just running around normally and rubberband. I also don't understand what the slider is supposed to be. Milliseconds, seconds, ticks, something else completely? Setting it to 40 does not pause regardless.

**To Reproduce**

Try to espeed on a nether highway with PauseOnLag configured.

**Other mods**
List other forge mods you are using (if any):

~~Abyss but this also happened before I used Abyss.~~ I don't use abyss anymore

**Expected behavior**

When a rubberband is detected, pause.

**Screenshots**

My autowalk config: 

![image](https://user-images.githubusercontent.com/29926144/126908692-5de8ac89-116d-4611-8608-4255da713a36.png)

**Comment by FluorideHistorian** [comment]
i believe this should have be fixed, reopen if not
