### ISSUE TITLE
[BUG] Strict Jesus Konas compatability issue

### ISSUE THREAD

**Issue by HarryPotter42MC** [RusherDevelopment/rusherhack-issues#985]
**Describe the bug**
The Jesus makes me 

**To Reproduce**
Have Konas and Rusherhack. use jesus mode strict

**Other mods**
Konas

**Expected behavior**
not be bumpy

**Screenshots**
Ask for the video in my dms: Harry_Potter_42#6811

**Additional context**
Ask for the video in my dms: Harry_Potter_42#6811

**Comment by FluorideHistorian** [comment]
reopen if strict is incompatible with boze in v2.0
